/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGameResponse_rating.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIGameResponse_rating::OAIGameResponse_rating(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIGameResponse_rating::OAIGameResponse_rating() {
    this->initializeModel();
}

OAIGameResponse_rating::~OAIGameResponse_rating() {}

void OAIGameResponse_rating::initializeModel() {

    m_mean_isSet = false;
    m_mean_isValid = false;

    m_count_isSet = false;
    m_count_isValid = false;

    m_mean_players_isSet = false;
    m_mean_players_isValid = false;

    m_count_players_isSet = false;
    m_count_players_isValid = false;

    m_mean_critics_isSet = false;
    m_mean_critics_isValid = false;

    m_count_critics_isSet = false;
    m_count_critics_isValid = false;
}

void OAIGameResponse_rating::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGameResponse_rating::fromJsonObject(QJsonObject json) {

    m_mean_isValid = ::OpenAPI::fromJsonValue(m_mean, json[QString("mean")]);
    m_mean_isSet = !json[QString("mean")].isNull() && m_mean_isValid;

    m_count_isValid = ::OpenAPI::fromJsonValue(m_count, json[QString("count")]);
    m_count_isSet = !json[QString("count")].isNull() && m_count_isValid;

    m_mean_players_isValid = ::OpenAPI::fromJsonValue(m_mean_players, json[QString("mean_players")]);
    m_mean_players_isSet = !json[QString("mean_players")].isNull() && m_mean_players_isValid;

    m_count_players_isValid = ::OpenAPI::fromJsonValue(m_count_players, json[QString("count_players")]);
    m_count_players_isSet = !json[QString("count_players")].isNull() && m_count_players_isValid;

    m_mean_critics_isValid = ::OpenAPI::fromJsonValue(m_mean_critics, json[QString("mean_critics")]);
    m_mean_critics_isSet = !json[QString("mean_critics")].isNull() && m_mean_critics_isValid;

    m_count_critics_isValid = ::OpenAPI::fromJsonValue(m_count_critics, json[QString("count_critics")]);
    m_count_critics_isSet = !json[QString("count_critics")].isNull() && m_count_critics_isValid;
}

QString OAIGameResponse_rating::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGameResponse_rating::asJsonObject() const {
    QJsonObject obj;
    if (m_mean_isSet) {
        obj.insert(QString("mean"), ::OpenAPI::toJsonValue(m_mean));
    }
    if (m_count_isSet) {
        obj.insert(QString("count"), ::OpenAPI::toJsonValue(m_count));
    }
    if (m_mean_players_isSet) {
        obj.insert(QString("mean_players"), ::OpenAPI::toJsonValue(m_mean_players));
    }
    if (m_count_players_isSet) {
        obj.insert(QString("count_players"), ::OpenAPI::toJsonValue(m_count_players));
    }
    if (m_mean_critics_isSet) {
        obj.insert(QString("mean_critics"), ::OpenAPI::toJsonValue(m_mean_critics));
    }
    if (m_count_critics_isSet) {
        obj.insert(QString("count_critics"), ::OpenAPI::toJsonValue(m_count_critics));
    }
    return obj;
}

float OAIGameResponse_rating::getMean() const {
    return m_mean;
}
void OAIGameResponse_rating::setMean(const float &mean) {
    m_mean = mean;
    m_mean_isSet = true;
}

bool OAIGameResponse_rating::is_mean_Set() const{
    return m_mean_isSet;
}

bool OAIGameResponse_rating::is_mean_Valid() const{
    return m_mean_isValid;
}

qint32 OAIGameResponse_rating::getCount() const {
    return m_count;
}
void OAIGameResponse_rating::setCount(const qint32 &count) {
    m_count = count;
    m_count_isSet = true;
}

bool OAIGameResponse_rating::is_count_Set() const{
    return m_count_isSet;
}

bool OAIGameResponse_rating::is_count_Valid() const{
    return m_count_isValid;
}

float OAIGameResponse_rating::getMeanPlayers() const {
    return m_mean_players;
}
void OAIGameResponse_rating::setMeanPlayers(const float &mean_players) {
    m_mean_players = mean_players;
    m_mean_players_isSet = true;
}

bool OAIGameResponse_rating::is_mean_players_Set() const{
    return m_mean_players_isSet;
}

bool OAIGameResponse_rating::is_mean_players_Valid() const{
    return m_mean_players_isValid;
}

qint32 OAIGameResponse_rating::getCountPlayers() const {
    return m_count_players;
}
void OAIGameResponse_rating::setCountPlayers(const qint32 &count_players) {
    m_count_players = count_players;
    m_count_players_isSet = true;
}

bool OAIGameResponse_rating::is_count_players_Set() const{
    return m_count_players_isSet;
}

bool OAIGameResponse_rating::is_count_players_Valid() const{
    return m_count_players_isValid;
}

float OAIGameResponse_rating::getMeanCritics() const {
    return m_mean_critics;
}
void OAIGameResponse_rating::setMeanCritics(const float &mean_critics) {
    m_mean_critics = mean_critics;
    m_mean_critics_isSet = true;
}

bool OAIGameResponse_rating::is_mean_critics_Set() const{
    return m_mean_critics_isSet;
}

bool OAIGameResponse_rating::is_mean_critics_Valid() const{
    return m_mean_critics_isValid;
}

qint32 OAIGameResponse_rating::getCountCritics() const {
    return m_count_critics;
}
void OAIGameResponse_rating::setCountCritics(const qint32 &count_critics) {
    m_count_critics = count_critics;
    m_count_critics_isSet = true;
}

bool OAIGameResponse_rating::is_count_critics_Set() const{
    return m_count_critics_isSet;
}

bool OAIGameResponse_rating::is_count_critics_Valid() const{
    return m_count_critics_isValid;
}

bool OAIGameResponse_rating::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_mean_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_count_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_mean_players_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_count_players_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_mean_critics_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_count_critics_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGameResponse_rating::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
