/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchResponse_sorting_options_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISearchResponse_sorting_options_inner::OAISearchResponse_sorting_options_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISearchResponse_sorting_options_inner::OAISearchResponse_sorting_options_inner() {
    this->initializeModel();
}

OAISearchResponse_sorting_options_inner::~OAISearchResponse_sorting_options_inner() {}

void OAISearchResponse_sorting_options_inner::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_sort_isSet = false;
    m_sort_isValid = false;

    m_key_isSet = false;
    m_key_isValid = false;
}

void OAISearchResponse_sorting_options_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchResponse_sorting_options_inner::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_sort_isValid = ::OpenAPI::fromJsonValue(m_sort, json[QString("sort")]);
    m_sort_isSet = !json[QString("sort")].isNull() && m_sort_isValid;

    m_key_isValid = ::OpenAPI::fromJsonValue(m_key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;
}

QString OAISearchResponse_sorting_options_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchResponse_sorting_options_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_sort_isSet) {
        obj.insert(QString("sort"), ::OpenAPI::toJsonValue(m_sort));
    }
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(m_key));
    }
    return obj;
}

QString OAISearchResponse_sorting_options_inner::getName() const {
    return m_name;
}
void OAISearchResponse_sorting_options_inner::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAISearchResponse_sorting_options_inner::is_name_Set() const{
    return m_name_isSet;
}

bool OAISearchResponse_sorting_options_inner::is_name_Valid() const{
    return m_name_isValid;
}

QString OAISearchResponse_sorting_options_inner::getSort() const {
    return m_sort;
}
void OAISearchResponse_sorting_options_inner::setSort(const QString &sort) {
    m_sort = sort;
    m_sort_isSet = true;
}

bool OAISearchResponse_sorting_options_inner::is_sort_Set() const{
    return m_sort_isSet;
}

bool OAISearchResponse_sorting_options_inner::is_sort_Valid() const{
    return m_sort_isValid;
}

QString OAISearchResponse_sorting_options_inner::getKey() const {
    return m_key;
}
void OAISearchResponse_sorting_options_inner::setKey(const QString &key) {
    m_key = key;
    m_key_isSet = true;
}

bool OAISearchResponse_sorting_options_inner::is_key_Set() const{
    return m_key_isSet;
}

bool OAISearchResponse_sorting_options_inner::is_key_Valid() const{
    return m_key_isValid;
}

bool OAISearchResponse_sorting_options_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_sort_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchResponse_sorting_options_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
