/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchResponse_sorting.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISearchResponse_sorting::OAISearchResponse_sorting(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISearchResponse_sorting::OAISearchResponse_sorting() {
    this->initializeModel();
}

OAISearchResponse_sorting::~OAISearchResponse_sorting() {}

void OAISearchResponse_sorting::initializeModel() {

    m_key_isSet = false;
    m_key_isValid = false;

    m_direction_isSet = false;
    m_direction_isValid = false;
}

void OAISearchResponse_sorting::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchResponse_sorting::fromJsonObject(QJsonObject json) {

    m_key_isValid = ::OpenAPI::fromJsonValue(m_key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_direction_isValid = ::OpenAPI::fromJsonValue(m_direction, json[QString("direction")]);
    m_direction_isSet = !json[QString("direction")].isNull() && m_direction_isValid;
}

QString OAISearchResponse_sorting::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchResponse_sorting::asJsonObject() const {
    QJsonObject obj;
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(m_key));
    }
    if (m_direction_isSet) {
        obj.insert(QString("direction"), ::OpenAPI::toJsonValue(m_direction));
    }
    return obj;
}

QString OAISearchResponse_sorting::getKey() const {
    return m_key;
}
void OAISearchResponse_sorting::setKey(const QString &key) {
    m_key = key;
    m_key_isSet = true;
}

bool OAISearchResponse_sorting::is_key_Set() const{
    return m_key_isSet;
}

bool OAISearchResponse_sorting::is_key_Valid() const{
    return m_key_isValid;
}

QString OAISearchResponse_sorting::getDirection() const {
    return m_direction;
}
void OAISearchResponse_sorting::setDirection(const QString &direction) {
    m_direction = direction;
    m_direction_isSet = true;
}

bool OAISearchResponse_sorting::is_direction_Set() const{
    return m_direction_isSet;
}

bool OAISearchResponse_sorting::is_direction_Valid() const{
    return m_direction_isValid;
}

bool OAISearchResponse_sorting::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_direction_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchResponse_sorting::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
