/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISimilarGamesResponse.h
 *
 * 
 */

#ifndef OAISimilarGamesResponse_H
#define OAISimilarGamesResponse_H

#include <QJsonObject>

#include "OAISearchResponse_results_inner.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchResponse_results_inner;

class OAISimilarGamesResponse : public OAIObject {
public:
    OAISimilarGamesResponse();
    OAISimilarGamesResponse(QString json);
    ~OAISimilarGamesResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAISearchResponse_results_inner> getResults() const;
    void setResults(const QList<OAISearchResponse_results_inner> &results);
    bool is_results_Set() const;
    bool is_results_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAISearchResponse_results_inner> m_results;
    bool m_results_isSet;
    bool m_results_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISimilarGamesResponse)

#endif // OAISimilarGamesResponse_H
