/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchSuggestionResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISearchSuggestionResponse::OAISearchSuggestionResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISearchSuggestionResponse::OAISearchSuggestionResponse() {
    this->initializeModel();
}

OAISearchSuggestionResponse::~OAISearchSuggestionResponse() {}

void OAISearchSuggestionResponse::initializeModel() {

    m_results_isSet = false;
    m_results_isValid = false;
}

void OAISearchSuggestionResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchSuggestionResponse::fromJsonObject(QJsonObject json) {

    m_results_isValid = ::OpenAPI::fromJsonValue(m_results, json[QString("results")]);
    m_results_isSet = !json[QString("results")].isNull() && m_results_isValid;
}

QString OAISearchSuggestionResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchSuggestionResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_results.size() > 0) {
        obj.insert(QString("results"), ::OpenAPI::toJsonValue(m_results));
    }
    return obj;
}

QList<OAISearchSuggestionResponse_results_inner> OAISearchSuggestionResponse::getResults() const {
    return m_results;
}
void OAISearchSuggestionResponse::setResults(const QList<OAISearchSuggestionResponse_results_inner> &results) {
    m_results = results;
    m_results_isSet = true;
}

bool OAISearchSuggestionResponse::is_results_Set() const{
    return m_results_isSet;
}

bool OAISearchSuggestionResponse::is_results_Valid() const{
    return m_results_isValid;
}

bool OAISearchSuggestionResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_results.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchSuggestionResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
