<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.makbn</groupId>
        <artifactId>mcp_mediator</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>mcp-mediator-implementation-query</artifactId>
    <name>MCP Mediator Query Implementation</name>
    <description>Query MCP Server: Public APIs Query implementation for MCP Mediator</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <docker-java.version>3.5.0</docker-java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.makbn</groupId>
            <artifactId>mcp-mediator-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.makbn</groupId>
            <artifactId>mcp-mediator-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>mcp-mediator-commons</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java-transport-httpclient5</artifactId>
            <version>${docker-java.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project> 