[project]
name = "mathematica-check"
version = "0.1.0"
requires-python = ">=3.11"
description = "A Python MCP server for interacting with Mathematica/wolframscript."
authors = [{ name = "Sirui Lu", email = "sirui.lu.phys@gmail.com" }]
license = { text = "MIT" }

dependencies = ["mcp[cli]>=1.0.0"]

[project.scripts]
mcp-mathematica-check = "mathematica_check.server:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
