=begin
#GameBrain API

#GameBrain API

The version of the OpenAPI document: 1.0.1
Contact: mail@gamebrain.co
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/game_news_item'
require 'openapi_client/models/game_news_response'
require 'openapi_client/models/game_response'
require 'openapi_client/models/game_response_offers_inner'
require 'openapi_client/models/game_response_offers_inner_price'
require 'openapi_client/models/game_response_official_stores_inner'
require 'openapi_client/models/game_response_platforms_inner'
require 'openapi_client/models/game_response_playtime'
require 'openapi_client/models/game_response_rating'
require 'openapi_client/models/search_response'
require 'openapi_client/models/search_response_active_filter_options_inner'
require 'openapi_client/models/search_response_active_filter_options_inner_values_inner'
require 'openapi_client/models/search_response_filter_options_inner'
require 'openapi_client/models/search_response_filter_options_inner_values_inner'
require 'openapi_client/models/search_response_results_inner'
require 'openapi_client/models/search_response_results_inner_rating'
require 'openapi_client/models/search_response_sorting'
require 'openapi_client/models/search_response_sorting_options_inner'
require 'openapi_client/models/search_suggestion_response'
require 'openapi_client/models/search_suggestion_response_results_inner'
require 'openapi_client/models/similar_games_response'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
