# HTTP configuration
quarkus.http.port=8080

# Application name
quarkus.application.name=car-management

# Logging configuration
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.category."com.carmanagement".level=DEBUG
quarkus.langchain4j.log-requests=false
quarkus.langchain4j.log-responses=false
# Development mode log level
%dev.quarkus.log.console.level=INFO
%dev.quarkus.log.category."dev.langchain4j.agentic".level=DEBUG

# port to expose in development mode
%dev.quarkus.http.port=8080

# Disable banner in console
quarkus.banner.enabled=false

# Static resources configuration
quarkus.http.static-resources.caching-enabled=false

# AI model configuration
quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.chat-model.temperature=0
quarkus.langchain4j.openai.timeout=PT180S
