[project]
name = "alibabacloud-dms-mcp-server"
version = "0.1.20"
description = "MCP Server for AlibabaCloud DMS"
readme = "README.md"
authors = [
    { name = "AlibabaCloud DMS" }
]
requires-python = ">=3.10"
dependencies = [
    "alibabacloud-dms-enterprise20181101>=1.76.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.1",
]

license = "Apache-2.0"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.9",
]

[project.scripts]
alibabacloud-dms-mcp-server = "alibabacloud_dms_mcp_server.server:run_server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[venv]
mode = "none"
