--[[
  GameBrain API

  GameBrain API

  The version of the OpenAPI document: 1.0.1
  Contact: mail@gamebrain.co
  Generated by: https://openapi-generator.tech
]]

-- game_response_official_stores_inner class
local game_response_official_stores_inner = {}
local game_response_official_stores_inner_mt = {
	__name = "game_response_official_stores_inner";
	__index = game_response_official_stores_inner;
}

local function cast_game_response_official_stores_inner(t)
	return setmetatable(t, game_response_official_stores_inner_mt)
end

local function new_game_response_official_stores_inner(source, url)
	return cast_game_response_official_stores_inner({
		["source"] = source;
		["url"] = url;
	})
end

return {
	cast = cast_game_response_official_stores_inner;
	new = new_game_response_official_stores_inner;
}
