--[[
  GameBrain API

  GameBrain API

  The version of the OpenAPI document: 1.0.1
  Contact: mail@gamebrain.co
  Generated by: https://openapi-generator.tech
]]

-- game_response_playtime class
local game_response_playtime = {}
local game_response_playtime_mt = {
	__name = "game_response_playtime";
	__index = game_response_playtime;
}

local function cast_game_response_playtime(t)
	return setmetatable(t, game_response_playtime_mt)
end

local function new_game_response_playtime(percentiles, min, median, max, mean, mentions)
	return cast_game_response_playtime({
		["percentiles"] = percentiles;
		["min"] = min;
		["median"] = median;
		["max"] = max;
		["mean"] = mean;
		["mentions"] = mentions;
	})
end

return {
	cast = cast_game_response_playtime;
	new = new_game_response_playtime;
}
