KEYWORDS = {
    "SELECTED_TOOLS": "SELECTED_TOOLS",
    "SELECTED_TOOL": "SELECTED_TOOL",
    "NO_TOOLS_SELECTED": "NO_TOOLS_SELECTED",
}
DEFAULT_NUM_RETRY = 3
DEFAULT_RETRY_PROMPT = "Please pay attention to the tools needed."
