/**
 * GameBrain API
 * GameBrain API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GameResponseOffersInnerPrice {
    'currency'?: string;
    'discountPercent'?: number;
    'value'?: number;
    'initial'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountPercent",
            "baseName": "discount_percent",
            "type": "number",
            "format": "float"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "initial",
            "baseName": "initial",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return GameResponseOffersInnerPrice.attributeTypeMap;
    }

    public constructor() {
    }
}

