/**
 * GameBrain API
 * GameBrain API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SearchResponseResultsInnerRating {
    'mean'?: number;
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mean",
            "baseName": "mean",
            "type": "number",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponseResultsInnerRating.attributeTypeMap;
    }

    public constructor() {
    }
}

