/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameResponseOffersInnerPrice } from './gameResponseOffersInnerPrice';


export interface GameResponseOffersInner { 
    price?: GameResponseOffersInnerPrice;
    store_name?: string;
    platform?: string;
    title?: string;
    url?: string;
}

