/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model

import co.gamebrain.client.model.SearchSuggestionResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param results 
 */


data class SearchSuggestionResponse (

    @Json(name = "results")
    val results: kotlin.collections.List<SearchSuggestionResponseResultsInner>? = null

) {


}

