FROM node:24-alpine AS builder

ARG NPM_REGISTRY=https://registry.npmjs.org/

WORKDIR /app

RUN npm config set registry ${NPM_REGISTRY} && npm install -g pnpm@10.7.1
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src
RUN pnpm exec tsc --build

FROM node:24-alpine AS runner
ENV NODE_ENV=production
ENV CONTAINERIZED=1
ENV CONTAINER_FILE_PATH=/mnt/host-downloads

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules/
COPY --from=builder /app/dist ./dist/

ENTRYPOINT ["node", "dist/index.js"]
