name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set package version
        run: echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' package.json) > package.json

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Set NPM_TOKEN
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: "!github.event.release.prerelease"
        run: |
          npm publish --access public

      - name: Publish release candidate
        if: "github.event.release.prerelease"
        run: |
          npm publish --access public --tag=canary
