
[project]
name = "binance-mcp-server"
version = "1.2.7"
description = "Binance's Model Context Protocol (MCP). Designed to support developers building crypto trading AI Agents."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "AnalyticAce (DOSSEH Shalom)", email = "dossehdosseh14@gmail.com" }
]
keywords = ["binance", "mcp", "server", "fastmcp", "crypto", "trading", "finance"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]
dependencies = [
    "fastmcp>=2.5.1",
    "python-binance>=1.0.29",
    "typer>=0.16.0",
]

[project.scripts]
binance-mcp-server = "binance_mcp_server.cli:app"

[project.urls]
Homepage = "https://analyticace.github.io/BinanceMCPServer/"
