/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import co.gamebrain.client.model.GameNewsResponse
import co.gamebrain.client.model.GameNewsItem

class GameNewsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GameNewsResponse
        //val modelInstance = GameNewsResponse()

        // to test the property `news`
        should("test news") {
            // uncomment below to test the property
            //modelInstance.news shouldBe ("TODO")
        }

    }
}
