/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import co.gamebrain.client.model.SearchResponseActiveFilterOptionsInner
import co.gamebrain.client.model.SearchResponseActiveFilterOptionsInnerValuesInner

class SearchResponseActiveFilterOptionsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchResponseActiveFilterOptionsInner
        //val modelInstance = SearchResponseActiveFilterOptionsInner()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `connection`
        should("test connection") {
            // uncomment below to test the property
            //modelInstance.connection shouldBe ("TODO")
        }

        // to test the property `propertyValues`
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
