[project]
name = "alation-ai-agent-mcp"
version = "1.0.0rc3"
description = "Alation Agent SDK with MCP support"
dependencies = [
  "alation-ai-agent-sdk>=1.0.0rc3",
  "mcp[cli]>=1.12.0",
  "fastMCP==2.14.0",
  "pydantic>=2.8.0,<2.12.0",
]
authors = [
  { name="Jagannath (Jags) Saragadam", email="jags.saragadam@alation.com"},
  { name="Lucy Eun", email="lucy.eun@alation.com"},
  { name="Ashwin Kumar Muruganandam", email="ashwin-kumar.muruganandam@alation.com"},
  { name="Adam Talmadge", email="adam.talmadge@alation.com"},
]
maintainers = [
  { name="Jagannath (Jags) Saragadam", email="jags.saragadam@alation.com"},
  { name="Lucy Eun", email="lucy.eun@alation.com"},
  { name="Ashwin Kumar Muruganandam", email="ashwin-kumar.muruganandam@alation.com"},
  { name="Adam Talmadge", email="adam.talmadge@alation.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License"
]
keywords = ["Alation", "AI Agent SDK", "Alation Agent Python SDK", "Alation AI Agent SDK"]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.8",
]
[project.scripts]
"start-alation-mcp-server" = "alation_ai_agent_mcp.server:run_server"
"start-mcp-server" = "alation_ai_agent_mcp.server:run_server" # Alias for backward compatibility

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["alation_ai_agent_mcp/"]

[tool.pdm.scripts]
test = "pytest tests/"

[project.urls]
Homepage = "https://github.com/Alation/alation-ai-agent-sdk/tree/main/python/dist-mcp"
Issues = "https://github.com/Alation/alation-ai-agent-sdk/issues"
Documentation = "https://github.com/Alation/alation-ai-agent-sdk/blob/main/python/dist-mcp/README.md"

[tool.ruff.lint]
ignore = ["TID252", "B021"]

[tool.uv.sources]
alation-ai-agent-sdk = { path = "../core-sdk" }
