/*
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.gamebrain.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameResponseOffersInnerPrice
 */
public class GameResponseOffersInnerPriceTest {
    private final GameResponseOffersInnerPrice model = new GameResponseOffersInnerPrice();

    /**
     * Model tests for GameResponseOffersInnerPrice
     */
    @Test
    public void testGameResponseOffersInnerPrice() {
        // TODO: test GameResponseOffersInnerPrice
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'discountPercent'
     */
    @Test
    public void discountPercentTest() {
        // TODO: test discountPercent
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'initial'
     */
    @Test
    public void initialTest() {
        // TODO: test initial
    }

}
