/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import co.gamebrain.client.model.GameResponsePlatformsInner

class GameResponsePlatformsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GameResponsePlatformsInner
        //val modelInstance = GameResponsePlatformsInner()

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
