[project]
name = "my-mcp-ssh"
version = "0.1.0"
description = "基于 MCP 协议的 SSH 连接工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "paramiko>=3.3.1",
]

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
