[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-deep-research" # PyPI 上的包名，需全网唯一
version = "0.1.0" # 每次发版都要改
description = "An MCP (Model-Context-Protocol) Server for Deep Academic Research"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Pb-207", email = "pengb0725@163.com"}]
dependencies = ["Flask", "html2text", "mcp", "playwright", "pydantic", "pyperclip"] # 运行时依赖

[project.urls]
"Homepage" = "https://github.com/Pb-207/mcp-deep-research"

[project.scripts]
mcp-deep-research = "mcp_deep_research.__main__:main"