[project]
name = "mcp-chess"
version = "0.1.9"
description = "MCP server for playing chess against AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.7.1",
    "chess==1.9.4",
    "uvicorn>=0.29.0",
    "cairosvg>=2.5.1",
    "Pillow>=10.0.0"
]

[project.scripts]
mcp-chess = "mcp_chess.server:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mcp_chess"]
