/**
 * GameBrain API
 * GameBrain API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchResponseResultsInnerRating } from '../models/SearchResponseResultsInnerRating';
import { HttpFile } from '../http/http';

export class SearchResponseResultsInner {
    'id'?: number;
    'year'?: number;
    'name'?: string;
    'genre'?: string;
    'image'?: string;
    'link'?: string;
    'rating'?: SearchResponseResultsInnerRating;
    'adultOnly'?: boolean;
    'screenshots'?: Array<string>;
    'microTrailer'?: string;
    'gameplay'?: string;
    'shortDescription'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "SearchResponseResultsInnerRating",
            "format": ""
        },
        {
            "name": "adultOnly",
            "baseName": "adult_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "screenshots",
            "baseName": "screenshots",
            "type": "Array<string>",
            "format": "uri"
        },
        {
            "name": "microTrailer",
            "baseName": "micro_trailer",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "gameplay",
            "baseName": "gameplay",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponseResultsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

