/**
 * GameBrain API
 * GameBrain API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchResponseResultsInner } from '../models/SearchResponseResultsInner';
import { HttpFile } from '../http/http';

export class SimilarGamesResponse {
    'results'?: Array<SearchResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SearchResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimilarGamesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

