/*
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.gamebrain.client.model;

import co.gamebrain.client.model.SearchResponseActiveFilterOptionsInner;
import co.gamebrain.client.model.SearchResponseFilterOptionsInner;
import co.gamebrain.client.model.SearchResponseResultsInner;
import co.gamebrain.client.model.SearchResponseSorting;
import co.gamebrain.client.model.SearchResponseSortingOptionsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchResponse
 */
public class SearchResponseTest {
    private final SearchResponse model = new SearchResponse();

    /**
     * Model tests for SearchResponse
     */
    @Test
    public void testSearchResponse() {
        // TODO: test SearchResponse
    }

    /**
     * Test the property 'sorting'
     */
    @Test
    public void sortingTest() {
        // TODO: test sorting
    }

    /**
     * Test the property 'activeFilterOptions'
     */
    @Test
    public void activeFilterOptionsTest() {
        // TODO: test activeFilterOptions
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'totalResults'
     */
    @Test
    public void totalResultsTest() {
        // TODO: test totalResults
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'filterOptions'
     */
    @Test
    public void filterOptionsTest() {
        // TODO: test filterOptions
    }

    /**
     * Test the property 'sortingOptions'
     */
    @Test
    public void sortingOptionsTest() {
        // TODO: test sortingOptions
    }

}
