# Generated constants from Python codebase
# Do not edit this file directly. Edit src/constants.py instead.

# Target organization
TARGET_ORG="mcp-research"

# Property name for last scan timestamp
GHAS_STATUS_UPDATED="GHAS_Status_Updated"

# Repository property names

# Total number of code scanning alerts
CODEALERTS="CodeAlerts"

# Total number of dependency alerts
DEPENDENCYALERTS="DependencyAlerts"

# Number of critical code scanning alerts
CODEALERTS_CRITICAL="CodeAlerts_Critical"

# Number of high code scanning alerts
CODEALERTS_HIGH="CodeAlerts_High"

# Number of medium code scanning alerts
CODEALERTS_MEDIUM="CodeAlerts_Medium"

# Number of low code scanning alerts
CODEALERTS_LOW="CodeAlerts_Low"

# Total number of secret scanning alerts
SECRETALERTS_TOTAL="SecretAlerts_Total"

# Number of secret scanning alerts by type
SECRETALERTS_BY_TYPE="SecretAlerts_By_Type"

# Number of critical dependency alerts
DEPENDENCYALERTS_CRITICAL="DependencyAlerts_Critical"

# Number of high dependency alerts
DEPENDENCYALERTS_HIGH="DependencyAlerts_High"

# Number of moderate dependency alerts
DEPENDENCYALERTS_MODERATE="DependencyAlerts_Moderate"

# Number of low dependency alerts
DEPENDENCYALERTS_LOW="DependencyAlerts_Low"
