/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package co.gamebrain.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SearchResponseFilterOptionsInnerValuesInner {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("key")
  private String key = null;
  @SerializedName("count")
  private BigDecimal count = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getCount() {
    return count;
  }
  public void setCount(BigDecimal count) {
    this.count = count;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponseFilterOptionsInnerValuesInner searchResponseFilterOptionsInnerValuesInner = (SearchResponseFilterOptionsInnerValuesInner) o;
    return (this.name == null ? searchResponseFilterOptionsInnerValuesInner.name == null : this.name.equals(searchResponseFilterOptionsInnerValuesInner.name)) &&
        (this.key == null ? searchResponseFilterOptionsInnerValuesInner.key == null : this.key.equals(searchResponseFilterOptionsInnerValuesInner.key)) &&
        (this.count == null ? searchResponseFilterOptionsInnerValuesInner.count == null : this.count.equals(searchResponseFilterOptionsInnerValuesInner.count));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    result = 31 * result + (this.count == null ? 0: this.count.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseFilterOptionsInnerValuesInner {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
