FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY python/examples/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./python/examples /app

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
