#!/usr/bin/env python3
"""
This script exports the constants from the Python codebase to a format consumable by shell scripts.
Run this script to generate a constants.sh file that can be sourced by shell scripts.
"""

from src.constants import Constants

def generate_shell_constants():
    """Generate a shell script with constants from the Python codebase."""
    lines = [
        "# Generated constants from Python codebase",
        "# Do not edit this file directly. Edit src/constants.py instead.",
        "",
        "# Target organization",
        f"TARGET_ORG=\"{Constants.Org.TARGET_ORG}\"",
        "",
        "# Property name for last scan timestamp",
        f"GHAS_STATUS_UPDATED=\"{Constants.ScanSettings.GHAS_STATUS_UPDATED}\"",
        ""
    ]

    # Add properties section header
    lines.append("# Repository property names")
    lines.append("")

    # Dynamically add all alert properties
    for prop in Constants.AlertProperties.get_all_properties():
        lines.append(f"# {prop['desc']}")
        lines.append(f"{prop['name'].upper()}=\"{prop['name']}\"")
        lines.append("")

    return "\n".join(lines)

if __name__ == "__main__":
    shell_constants = generate_shell_constants()
    with open("constants.sh", "w") as f:
        f.write(shell_constants)
    print("Generated constants.sh file for shell scripts.")
