/**
 * Investor relevance lexicon used to filter lifestyle content before scoring.
 * Inclusion terms contribute weighted relevance; exclusion terms disqualify headlines outright.
 */
export const INVESTOR_RELEVANCE = {
  inclusion: {
    // Economic indicators and macro drivers
    'gdp': 2,
    'inflation': 2,
    'interest rate': 2,
    'fed': 2,
    'federal reserve': 2,
    'treasury': 2,
    'bond': 2,
    'yield': 2,
    'market': 1,
    'index': 1,
    'dow': 2,
    'nasdaq': 2,
    's&p': 2,
    'stock': 1,

    // Corporate finance and business
    'earnings': 2,
    'revenue': 2,
    'profit': 2,
    'loss': 2,
    'merger': 2,
    'acquisition': 2,
    'ipo': 2,
    'investment': 1,
    'investor': 1,
    'dividend': 2,
    'valuation': 2,
    'shares': 1,
    'stake': 1,

    // Real estate specific
    'real estate': 2,
    'property': 1,
    'commercial': 1,
    'retail space': 2,
    'office': 1,
    'lease': 1,
    'tenant': 1,
    'development': 1,
    'construction': 1,

    // Economic conditions
    'recession': 2,
    'growth': 1,
    'economy': 1,
    'economic': 1,
    'unemployment': 2,
    'jobs': 1,
    'labor market': 2,
    'consumer spending': 2,
    'retail sales': 2,

    // Regulatory and policy
    'sec': 2,
    'regulation': 2,
    'policy': 1,
    'tax': 1,
    'legislation': 1,
    'reform': 1,
    'compliance': 1,
  },
  exclusion: [
    'recipe',
    'cooking',
    'food',
    'restaurant',
    'diet',
    'fitness',
    'exercise',
    'workout',
    'celebrity',
    'actor',
    'actress',
    'movie',
    'film',
    'tv show',
    'television',
    'entertainment',
    'music',
    'song',
    'album',
    'concert',
    'sports',
    'game',
    'match',
    'player',
    'team',
    'score',
    'lifestyle',
    'fashion',
    'beauty',
    'travel',
    'vacation',
    'holiday',
    'beach',
    'weather',
    'pet',
    'animal',
    'garden',
    'home decor',
    'dating',
    'relationship',
    'wedding',
    'viral',
    'social media',
    'influencer',
    'tiktok',
    'instagram',
    'youtube',
  ],
} as const;

export type InvestorInclusionTerm = keyof typeof INVESTOR_RELEVANCE.inclusion;
