# coding: utf-8

"""
    GameBrain API

    GameBrain API

    The version of the OpenAPI document: 1.0.1
    Contact: mail@gamebrain.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gamebrain.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_detail(self) -> None:
        """Test case for detail

        Get Game Details
        """
        pass

    def test_news(self) -> None:
        """Test case for news

        Get Game News
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search Games
        """
        pass

    def test_similar(self) -> None:
        """Test case for similar

        Get Similar Games
        """
        pass

    def test_suggest(self) -> None:
        """Test case for suggest

        Get Game Suggestions
        """
        pass


if __name__ == '__main__':
    unittest.main()
