name: goreleaser

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_AUTH_TOKEN }}
      - name: Publish to npm
        uses: evg4b/goreleaser-npm-publisher-action@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          prefix: '@chaindead'
          description: Telegram MCP server with API integration for accessing user data, managing dialogs (chats, channels, groups), retrieving messages, and handling read status.
          files: |-
            LICENSE
            README.md