=begin
#GameBrain API

#GameBrain API

The version of the OpenAPI document: 1.0.1
Contact: mail@gamebrain.co
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for detail
  # Get Game Details
  # Get all the details about a game given its id. Details include screenshots, ratings, release dates, videos, description, tags, and much more.
  # @param id The unique identifier of the game.
  # @param api_key Your API key for authentication.
  # @param [Hash] opts the optional parameters
  # @return [GameResponse]
  describe 'detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for news
  # Get Game News
  # Get news related to the given game.
  # @param id 
  # @param offset 
  # @param limit 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [GameNewsResponse]
  describe 'news test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search
  # Search Games
  # Search hundreds of thousands of video games from over 70 platforms. The query can be a game name, a platform, a genre, or any combination
  # @param query The search query, e.g., game name, platform, genre, or any combination.
  # @param offset The number of results to skip before starting to collect the result set. Between 0 and 1000.
  # @param limit The maximum number of results to return between 1 and 10.
  # @param filters JSON array of filter objects to apply to the search.
  # @param sort The field by which to sort the results, either computed_rating, price, or release_date
  # @param sort_order The sort order: &#39;asc&#39; for ascending or &#39;desc&#39; for descending.
  # @param generate_filter_options Whether to generate filter options in the response.
  # @param api_key Your API key for authentication.
  # @param [Hash] opts the optional parameters
  # @return [SearchResponse]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for similar
  # Get Similar Games
  # Get games that are similar to the given one.
  # @param id 
  # @param limit 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [SimilarGamesResponse]
  describe 'similar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for suggest
  # Get Game Suggestions
  # Get game suggestions based on (partial) search queries. For example, the query &#39;gt&#39; will return games like GTA.
  # @param query The partial search query to get suggestions for.
  # @param limit The maximum number of suggestions to return.
  # @param api_key Your API key for authentication.
  # @param [Hash] opts the optional parameters
  # @return [SearchSuggestionResponse]
  describe 'suggest test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
