--[[
  GameBrain API

  GameBrain API

  The version of the OpenAPI document: 1.0.1
  Contact: mail@gamebrain.co
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for gamebrain.model.search_response_filter_options_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("search_response_filter_options_inner", function()
  local gamebrain_search_response_filter_options_inner = require "gamebrain.model.search_response_filter_options_inner"

  -- unit tests for the property 'name'
  describe("property name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'key'
  describe("property key test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'values'
  describe("property values test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
