[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-simple-openai-assistant"
version = "0.4.1"
authors = [
    {name = "Andy Brandt", email = "andy@codesprinters.com"}
]
description = "A simple MCP server for interacting with OpenAI assistants"
readme = "README.md"
requires-python = ">=3.10"
license="MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastmcp>=2.10.0",
    "openai>=1.0.0"
]

[project.optional-dependencies]
dev = [
    "python-dotenv",
    "pytest",
    "pytest-asyncio"
]

[project.scripts]
mcp-simple-openai-assistant = "mcp_simple_openai_assistant.__main__:main"