--[[
  GameBrain API

  GameBrain API

  The version of the OpenAPI document: 1.0.1
  Contact: mail@gamebrain.co
  Generated by: https://openapi-generator.tech
]]

-- game_response class
local game_response = {}
local game_response_mt = {
	__name = "game_response";
	__index = game_response;
}

local function cast_game_response(t)
	return setmetatable(t, game_response_mt)
end

local function new_game_response(id, name, image, gameplay, link, x_url, rating, description, short_description, release_date, developer, playtime, platforms, tags, genres, genre, themes, adult_only, play_modes, screenshots, videos, offers, official_stores, micro_trailer)
	return cast_game_response({
		["id"] = id;
		["name"] = name;
		["image"] = image;
		["gameplay"] = gameplay;
		["link"] = link;
		["x_url"] = x_url;
		["rating"] = rating;
		["description"] = description;
		["short_description"] = short_description;
		["release_date"] = release_date;
		["developer"] = developer;
		["playtime"] = playtime;
		["platforms"] = platforms;
		["tags"] = tags;
		["genres"] = genres;
		["genre"] = genre;
		["themes"] = themes;
		["adult_only"] = adult_only;
		["play_modes"] = play_modes;
		["screenshots"] = screenshots;
		["videos"] = videos;
		["offers"] = offers;
		["official_stores"] = official_stores;
		["micro_trailer"] = micro_trailer;
	})
end

return {
	cast = cast_game_response;
	new = new_game_response;
}
