/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GamebrainJs);
  }
}(this, function(expect, GamebrainJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GamebrainJs.GameResponsePlaytime();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameResponsePlaytime', function() {
    it('should create an instance of GameResponsePlaytime', function() {
      // uncomment below and update the code to test GameResponsePlaytime
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be.a(GamebrainJs.GameResponsePlaytime);
    });

    it('should have the property percentiles (base name: "percentiles")', function() {
      // uncomment below and update the code to test the property percentiles
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

    it('should have the property min (base name: "min")', function() {
      // uncomment below and update the code to test the property min
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

    it('should have the property median (base name: "median")', function() {
      // uncomment below and update the code to test the property median
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

    it('should have the property mean (base name: "mean")', function() {
      // uncomment below and update the code to test the property mean
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

    it('should have the property mentions (base name: "mentions")', function() {
      // uncomment below and update the code to test the property mentions
      //var instance = new GamebrainJs.GameResponsePlaytime();
      //expect(instance).to.be();
    });

  });

}));
