# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GameBrainAPI.Model.SearchResponseFilterOptionsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :key,
    :values
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :key => String.t | nil,
    :values => [GameBrainAPI.Model.SearchResponseFilterOptionsInnerValuesInner.t] | nil
  }

  alias GameBrainAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:values, :list, GameBrainAPI.Model.SearchResponseFilterOptionsInnerValuesInner)
  end
end

