# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GameBrainAPI.Model.SearchResponseSortingOptionsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :sort,
    :key
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :sort => String.t | nil,
    :key => String.t | nil
  }

  def decode(value) do
    value
  end
end

