# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GameBrainAPI.Model.SearchResponseSorting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :key,
    :direction
  ]

  @type t :: %__MODULE__{
    :key => String.t | nil,
    :direction => String.t | nil
  }

  def decode(value) do
    value
  end
end

