# coding: utf-8

"""
    GameBrain API

    GameBrain API

    The version of the OpenAPI document: 1.0.1
    Contact: mail@gamebrain.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gamebrain.models.game_news_response import GameNewsResponse

class TestGameNewsResponse(unittest.TestCase):
    """GameNewsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameNewsResponse:
        """Test GameNewsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameNewsResponse`
        """
        model = GameNewsResponse()
        if include_optional:
            return GameNewsResponse(
                news = [
                    gamebrain.models.game_news_item.GameNewsItem(
                        title = '', 
                        url = '', 
                        source = '', 
                        image = '', 
                        published = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ]
            )
        else:
            return GameNewsResponse(
                news = [
                    gamebrain.models.game_news_item.GameNewsItem(
                        title = '', 
                        url = '', 
                        source = '', 
                        image = '', 
                        published = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
        )
        """

    def testGameNewsResponse(self):
        """Test GameNewsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
