# coding: utf-8

"""
    GameBrain API

    GameBrain API

    The version of the OpenAPI document: 1.0.1
    Contact: mail@gamebrain.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gamebrain.models.search_response_active_filter_options_inner import SearchResponseActiveFilterOptionsInner

class TestSearchResponseActiveFilterOptionsInner(unittest.TestCase):
    """SearchResponseActiveFilterOptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchResponseActiveFilterOptionsInner:
        """Test SearchResponseActiveFilterOptionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchResponseActiveFilterOptionsInner`
        """
        model = SearchResponseActiveFilterOptionsInner()
        if include_optional:
            return SearchResponseActiveFilterOptionsInner(
                key = '',
                connection = '',
                values = [
                    gamebrain.models.search_response_active_filter_options_inner_values_inner.SearchResponse_active_filter_options_inner_values_inner(
                        match = '', 
                        value = '', )
                    ]
            )
        else:
            return SearchResponseActiveFilterOptionsInner(
        )
        """

    def testSearchResponseActiveFilterOptionsInner(self):
        """Test SearchResponseActiveFilterOptionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
