# coding: utf-8

"""
    GameBrain API

    GameBrain API

    The version of the OpenAPI document: 1.0.1
    Contact: mail@gamebrain.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gamebrain.models.game_response_offers_inner_price import GameResponseOffersInnerPrice

class TestGameResponseOffersInnerPrice(unittest.TestCase):
    """GameResponseOffersInnerPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameResponseOffersInnerPrice:
        """Test GameResponseOffersInnerPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameResponseOffersInnerPrice`
        """
        model = GameResponseOffersInnerPrice()
        if include_optional:
            return GameResponseOffersInnerPrice(
                currency = '',
                discount_percent = 1.337,
                value = 1.337,
                initial = 1.337
            )
        else:
            return GameResponseOffersInnerPrice(
        )
        """

    def testGameResponseOffersInnerPrice(self):
        """Test GameResponseOffersInnerPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
