[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "osp-marketing-tools"
version = "0.1.0"
description = "OSP Marketing Tools using Model Context Protocol"
authors = [
    {name = "Robert Douglass, Tracy Evans, Jeffrey McGuire, other Open Srategy Partners contributors"}
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "mcp[cli]",
    "aiohttp==3.11.11"
]

[project.scripts]
osp_marketing_tools = "osp_marketing_tools.server:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/osp_marketing_tools"]