--[[
  GameBrain API

  GameBrain API

  The version of the OpenAPI document: 1.0.1
  Contact: mail@gamebrain.co
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for gamebrain.model.search_response_active_filter_options_inner_values_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("search_response_active_filter_options_inner_values_inner", function()
  local gamebrain_search_response_active_filter_options_inner_values_inner = require "gamebrain.model.search_response_active_filter_options_inner_values_inner"

  -- unit tests for the property 'match'
  describe("property match test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'value'
  describe("property value test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
