[project]
name = "assignment25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "google-auth-oauthlib>=1.2.1",
    "google-generativeai>=0.8.5",
    "mcp>=1.6.0",
    "pillow>=11.2.1",
    "pyautogui>=0.9.54",
    "pydantic>=2.11.3",
    "screeninfo>=0.8.1",
    "selenium>=4.31.0",
    "webdriver-manager>=4.0.2",
]
