/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchResponseFilterOptionsInnerValuesInner from './SearchResponseFilterOptionsInnerValuesInner';

/**
 * The SearchResponseFilterOptionsInner model module.
 * @module model/SearchResponseFilterOptionsInner
 * @version 1.0.2
 */
class SearchResponseFilterOptionsInner {
    /**
     * Constructs a new <code>SearchResponseFilterOptionsInner</code>.
     * @alias module:model/SearchResponseFilterOptionsInner
     */
    constructor() { 
        
        SearchResponseFilterOptionsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchResponseFilterOptionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchResponseFilterOptionsInner} obj Optional instance to populate.
     * @return {module:model/SearchResponseFilterOptionsInner} The populated <code>SearchResponseFilterOptionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchResponseFilterOptionsInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [SearchResponseFilterOptionsInnerValuesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchResponseFilterOptionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchResponseFilterOptionsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        if (data['values']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['values'])) {
                throw new Error("Expected the field `values` to be an array in the JSON data but got " + data['values']);
            }
            // validate the optional field `values` (array)
            for (const item of data['values']) {
                SearchResponseFilterOptionsInnerValuesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} name
 */
SearchResponseFilterOptionsInner.prototype['name'] = undefined;

/**
 * @member {String} key
 */
SearchResponseFilterOptionsInner.prototype['key'] = undefined;

/**
 * @member {Array.<module:model/SearchResponseFilterOptionsInnerValuesInner>} values
 */
SearchResponseFilterOptionsInner.prototype['values'] = undefined;






export default SearchResponseFilterOptionsInner;

