/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import GameNewsItem from './model/GameNewsItem';
import GameNewsResponse from './model/GameNewsResponse';
import GameResponse from './model/GameResponse';
import GameResponseOffersInner from './model/GameResponseOffersInner';
import GameResponseOffersInnerPrice from './model/GameResponseOffersInnerPrice';
import GameResponseOfficialStoresInner from './model/GameResponseOfficialStoresInner';
import GameResponsePlatformsInner from './model/GameResponsePlatformsInner';
import GameResponsePlaytime from './model/GameResponsePlaytime';
import GameResponseRating from './model/GameResponseRating';
import SearchResponse from './model/SearchResponse';
import SearchResponseActiveFilterOptionsInner from './model/SearchResponseActiveFilterOptionsInner';
import SearchResponseActiveFilterOptionsInnerValuesInner from './model/SearchResponseActiveFilterOptionsInnerValuesInner';
import SearchResponseFilterOptionsInner from './model/SearchResponseFilterOptionsInner';
import SearchResponseFilterOptionsInnerValuesInner from './model/SearchResponseFilterOptionsInnerValuesInner';
import SearchResponseResultsInner from './model/SearchResponseResultsInner';
import SearchResponseResultsInnerRating from './model/SearchResponseResultsInnerRating';
import SearchResponseSorting from './model/SearchResponseSorting';
import SearchResponseSortingOptionsInner from './model/SearchResponseSortingOptionsInner';
import SearchSuggestionResponse from './model/SearchSuggestionResponse';
import SearchSuggestionResponseResultsInner from './model/SearchSuggestionResponseResultsInner';
import SimilarGamesResponse from './model/SimilarGamesResponse';
import DefaultApi from './api/DefaultApi';


/**
* GameBrain API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GamebrainJs = require('index'); // See note below*.
* var xxxSvc = new GamebrainJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GamebrainJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GamebrainJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GamebrainJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The GameNewsItem model constructor.
     * @property {module:model/GameNewsItem}
     */
    GameNewsItem,

    /**
     * The GameNewsResponse model constructor.
     * @property {module:model/GameNewsResponse}
     */
    GameNewsResponse,

    /**
     * The GameResponse model constructor.
     * @property {module:model/GameResponse}
     */
    GameResponse,

    /**
     * The GameResponseOffersInner model constructor.
     * @property {module:model/GameResponseOffersInner}
     */
    GameResponseOffersInner,

    /**
     * The GameResponseOffersInnerPrice model constructor.
     * @property {module:model/GameResponseOffersInnerPrice}
     */
    GameResponseOffersInnerPrice,

    /**
     * The GameResponseOfficialStoresInner model constructor.
     * @property {module:model/GameResponseOfficialStoresInner}
     */
    GameResponseOfficialStoresInner,

    /**
     * The GameResponsePlatformsInner model constructor.
     * @property {module:model/GameResponsePlatformsInner}
     */
    GameResponsePlatformsInner,

    /**
     * The GameResponsePlaytime model constructor.
     * @property {module:model/GameResponsePlaytime}
     */
    GameResponsePlaytime,

    /**
     * The GameResponseRating model constructor.
     * @property {module:model/GameResponseRating}
     */
    GameResponseRating,

    /**
     * The SearchResponse model constructor.
     * @property {module:model/SearchResponse}
     */
    SearchResponse,

    /**
     * The SearchResponseActiveFilterOptionsInner model constructor.
     * @property {module:model/SearchResponseActiveFilterOptionsInner}
     */
    SearchResponseActiveFilterOptionsInner,

    /**
     * The SearchResponseActiveFilterOptionsInnerValuesInner model constructor.
     * @property {module:model/SearchResponseActiveFilterOptionsInnerValuesInner}
     */
    SearchResponseActiveFilterOptionsInnerValuesInner,

    /**
     * The SearchResponseFilterOptionsInner model constructor.
     * @property {module:model/SearchResponseFilterOptionsInner}
     */
    SearchResponseFilterOptionsInner,

    /**
     * The SearchResponseFilterOptionsInnerValuesInner model constructor.
     * @property {module:model/SearchResponseFilterOptionsInnerValuesInner}
     */
    SearchResponseFilterOptionsInnerValuesInner,

    /**
     * The SearchResponseResultsInner model constructor.
     * @property {module:model/SearchResponseResultsInner}
     */
    SearchResponseResultsInner,

    /**
     * The SearchResponseResultsInnerRating model constructor.
     * @property {module:model/SearchResponseResultsInnerRating}
     */
    SearchResponseResultsInnerRating,

    /**
     * The SearchResponseSorting model constructor.
     * @property {module:model/SearchResponseSorting}
     */
    SearchResponseSorting,

    /**
     * The SearchResponseSortingOptionsInner model constructor.
     * @property {module:model/SearchResponseSortingOptionsInner}
     */
    SearchResponseSortingOptionsInner,

    /**
     * The SearchSuggestionResponse model constructor.
     * @property {module:model/SearchSuggestionResponse}
     */
    SearchSuggestionResponse,

    /**
     * The SearchSuggestionResponseResultsInner model constructor.
     * @property {module:model/SearchSuggestionResponseResultsInner}
     */
    SearchSuggestionResponseResultsInner,

    /**
     * The SimilarGamesResponse model constructor.
     * @property {module:model/SimilarGamesResponse}
     */
    SimilarGamesResponse,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
