/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package co.gamebrain.client.model;

import java.net.URI;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GameResponseOfficialStoresInner {
  
  @SerializedName("source")
  private String source = null;
  @SerializedName("url")
  private URI url = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }
  public void setSource(String source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getUrl() {
    return url;
  }
  public void setUrl(URI url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameResponseOfficialStoresInner gameResponseOfficialStoresInner = (GameResponseOfficialStoresInner) o;
    return (this.source == null ? gameResponseOfficialStoresInner.source == null : this.source.equals(gameResponseOfficialStoresInner.source)) &&
        (this.url == null ? gameResponseOfficialStoresInner.url == null : this.url.equals(gameResponseOfficialStoresInner.url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.source == null ? 0: this.source.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameResponseOfficialStoresInner {\n");
    
    sb.append("  source: ").append(source).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
