/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package co.gamebrain.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SearchResponseSortingOptionsInner {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("sort")
  private String sort = null;
  @SerializedName("key")
  private String key = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSort() {
    return sort;
  }
  public void setSort(String sort) {
    this.sort = sort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponseSortingOptionsInner searchResponseSortingOptionsInner = (SearchResponseSortingOptionsInner) o;
    return (this.name == null ? searchResponseSortingOptionsInner.name == null : this.name.equals(searchResponseSortingOptionsInner.name)) &&
        (this.sort == null ? searchResponseSortingOptionsInner.sort == null : this.sort.equals(searchResponseSortingOptionsInner.sort)) &&
        (this.key == null ? searchResponseSortingOptionsInner.key == null : this.key.equals(searchResponseSortingOptionsInner.key));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.sort == null ? 0: this.sort.hashCode());
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseSortingOptionsInner {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  sort: ").append(sort).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
