/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package co.gamebrain.client.model;

import co.gamebrain.client.model.SearchResponseResultsInnerRating;
import java.math.BigDecimal;
import java.net.URI;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SearchSuggestionResponseResultsInner {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("year")
  private BigDecimal year = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("genre")
  private String genre = null;
  @SerializedName("image")
  private URI image = null;
  @SerializedName("link")
  private String link = null;
  @SerializedName("rating")
  private SearchResponseResultsInnerRating rating = null;
  @SerializedName("adult_only")
  private Boolean adultOnly = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getYear() {
    return year;
  }
  public void setYear(BigDecimal year) {
    this.year = year;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGenre() {
    return genre;
  }
  public void setGenre(String genre) {
    this.genre = genre;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getImage() {
    return image;
  }
  public void setImage(URI image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLink() {
    return link;
  }
  public void setLink(String link) {
    this.link = link;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SearchResponseResultsInnerRating getRating() {
    return rating;
  }
  public void setRating(SearchResponseResultsInnerRating rating) {
    this.rating = rating;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAdultOnly() {
    return adultOnly;
  }
  public void setAdultOnly(Boolean adultOnly) {
    this.adultOnly = adultOnly;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSuggestionResponseResultsInner searchSuggestionResponseResultsInner = (SearchSuggestionResponseResultsInner) o;
    return (this.id == null ? searchSuggestionResponseResultsInner.id == null : this.id.equals(searchSuggestionResponseResultsInner.id)) &&
        (this.year == null ? searchSuggestionResponseResultsInner.year == null : this.year.equals(searchSuggestionResponseResultsInner.year)) &&
        (this.name == null ? searchSuggestionResponseResultsInner.name == null : this.name.equals(searchSuggestionResponseResultsInner.name)) &&
        (this.genre == null ? searchSuggestionResponseResultsInner.genre == null : this.genre.equals(searchSuggestionResponseResultsInner.genre)) &&
        (this.image == null ? searchSuggestionResponseResultsInner.image == null : this.image.equals(searchSuggestionResponseResultsInner.image)) &&
        (this.link == null ? searchSuggestionResponseResultsInner.link == null : this.link.equals(searchSuggestionResponseResultsInner.link)) &&
        (this.rating == null ? searchSuggestionResponseResultsInner.rating == null : this.rating.equals(searchSuggestionResponseResultsInner.rating)) &&
        (this.adultOnly == null ? searchSuggestionResponseResultsInner.adultOnly == null : this.adultOnly.equals(searchSuggestionResponseResultsInner.adultOnly));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.year == null ? 0: this.year.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.genre == null ? 0: this.genre.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.link == null ? 0: this.link.hashCode());
    result = 31 * result + (this.rating == null ? 0: this.rating.hashCode());
    result = 31 * result + (this.adultOnly == null ? 0: this.adultOnly.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSuggestionResponseResultsInner {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  year: ").append(year).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  genre: ").append(genre).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  link: ").append(link).append("\n");
    sb.append("  rating: ").append(rating).append("\n");
    sb.append("  adultOnly: ").append(adultOnly).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
