[project]
name = "mcp-server-baidu-maps"
version = "0.2.4"
description = "MCP Server Baidu Maps"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "baidu-maps" }]
maintainers = [{ name = "Pineapple274", email = "yuyangyang3838@gmail.com" }]
keywords = ["http", "mcp", "map", "baidu"]
license = { text = "MIT" }
dependencies = [
    "mcp[cli]>=1.9.0",
]

[project.scripts]
mcp-server-baidu-maps = "mcp_server_baidu_maps:main"

