kind: Task
metadata:
  labels:
    suite: kiali
  name: "Show topology for multiple namespaces"
  category: "High-Level Observability & Health"
  difficulty: easy
steps:
  setup:
    inline: |-
      #!/usr/bin/env bash
  verify:
    contains: "topology"
  cleanup:
    inline: |-
      #!/usr/bin/env bash
  prompt:
    inline: Show me the topology for the bookinfo and default namespaces together.
