<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.langchain4j</groupId>
    <artifactId>quarkus-workshop-langchain4j</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <modules>
        <module>section-1/step-01</module>
        <module>section-1/step-02</module>
        <module>section-1/step-03</module>
        <module>section-1/step-04</module>
        <module>section-1/step-05</module>
        <module>section-1/step-06</module>
        <module>section-1/step-07</module>
        <module>section-1/step-08</module>
        <module>section-1/step-08-mcp-server</module>
        <module>section-1/step-09</module>
        <module>section-1/step-10</module>
        <module>section-1/step-11</module>
        <module>section-2/step-01</module>
        <module>section-2/step-02</module>
        <module>section-2/step-03</module>
        <module>section-2/step-04</module>
        <module>section-2/step-05/multi-agent-system</module>
        <module>section-2/step-05/remote-a2a-agent</module>
        <module>section-2/step-06</module>
    </modules>
</project>
