/*
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.gamebrain.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import co.gamebrain.client.JSON;

/**
 * GameResponseRating
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
public class GameResponseRating {
  public static final String SERIALIZED_NAME_MEAN = "mean";
  @SerializedName(SERIALIZED_NAME_MEAN)
  private Float mean;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_MEAN_PLAYERS = "mean_players";
  @SerializedName(SERIALIZED_NAME_MEAN_PLAYERS)
  private Float meanPlayers;

  public static final String SERIALIZED_NAME_COUNT_PLAYERS = "count_players";
  @SerializedName(SERIALIZED_NAME_COUNT_PLAYERS)
  private Integer countPlayers;

  public static final String SERIALIZED_NAME_MEAN_CRITICS = "mean_critics";
  @SerializedName(SERIALIZED_NAME_MEAN_CRITICS)
  private Float meanCritics;

  public static final String SERIALIZED_NAME_COUNT_CRITICS = "count_critics";
  @SerializedName(SERIALIZED_NAME_COUNT_CRITICS)
  private Integer countCritics;

  public GameResponseRating() {
  }

  public GameResponseRating mean(Float mean) {
    this.mean = mean;
    return this;
  }

  /**
   * Get mean
   * @return mean
   */
  @javax.annotation.Nullable
  public Float getMean() {
    return mean;
  }

  public void setMean(Float mean) {
    this.mean = mean;
  }


  public GameResponseRating count(Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nullable
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  public GameResponseRating meanPlayers(Float meanPlayers) {
    this.meanPlayers = meanPlayers;
    return this;
  }

  /**
   * Get meanPlayers
   * @return meanPlayers
   */
  @javax.annotation.Nullable
  public Float getMeanPlayers() {
    return meanPlayers;
  }

  public void setMeanPlayers(Float meanPlayers) {
    this.meanPlayers = meanPlayers;
  }


  public GameResponseRating countPlayers(Integer countPlayers) {
    this.countPlayers = countPlayers;
    return this;
  }

  /**
   * Get countPlayers
   * @return countPlayers
   */
  @javax.annotation.Nullable
  public Integer getCountPlayers() {
    return countPlayers;
  }

  public void setCountPlayers(Integer countPlayers) {
    this.countPlayers = countPlayers;
  }


  public GameResponseRating meanCritics(Float meanCritics) {
    this.meanCritics = meanCritics;
    return this;
  }

  /**
   * Get meanCritics
   * @return meanCritics
   */
  @javax.annotation.Nullable
  public Float getMeanCritics() {
    return meanCritics;
  }

  public void setMeanCritics(Float meanCritics) {
    this.meanCritics = meanCritics;
  }


  public GameResponseRating countCritics(Integer countCritics) {
    this.countCritics = countCritics;
    return this;
  }

  /**
   * Get countCritics
   * @return countCritics
   */
  @javax.annotation.Nullable
  public Integer getCountCritics() {
    return countCritics;
  }

  public void setCountCritics(Integer countCritics) {
    this.countCritics = countCritics;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameResponseRating gameResponseRating = (GameResponseRating) o;
    return Objects.equals(this.mean, gameResponseRating.mean) &&
        Objects.equals(this.count, gameResponseRating.count) &&
        Objects.equals(this.meanPlayers, gameResponseRating.meanPlayers) &&
        Objects.equals(this.countPlayers, gameResponseRating.countPlayers) &&
        Objects.equals(this.meanCritics, gameResponseRating.meanCritics) &&
        Objects.equals(this.countCritics, gameResponseRating.countCritics);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(mean, count, meanPlayers, countPlayers, meanCritics, countCritics);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameResponseRating {\n");
    sb.append("    mean: ").append(toIndentedString(mean)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    meanPlayers: ").append(toIndentedString(meanPlayers)).append("\n");
    sb.append("    countPlayers: ").append(toIndentedString(countPlayers)).append("\n");
    sb.append("    meanCritics: ").append(toIndentedString(meanCritics)).append("\n");
    sb.append("    countCritics: ").append(toIndentedString(countCritics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mean");
    openapiFields.add("count");
    openapiFields.add("mean_players");
    openapiFields.add("count_players");
    openapiFields.add("mean_critics");
    openapiFields.add("count_critics");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GameResponseRating
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GameResponseRating.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GameResponseRating is not found in the empty JSON string", GameResponseRating.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GameResponseRating.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GameResponseRating` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GameResponseRating.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GameResponseRating' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GameResponseRating> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GameResponseRating.class));

       return (TypeAdapter<T>) new TypeAdapter<GameResponseRating>() {
           @Override
           public void write(JsonWriter out, GameResponseRating value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GameResponseRating read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GameResponseRating given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GameResponseRating
   * @throws IOException if the JSON string is invalid with respect to GameResponseRating
   */
  public static GameResponseRating fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GameResponseRating.class);
  }

  /**
   * Convert an instance of GameResponseRating to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

