repos:
  - repo: local
    hooks:
      - id: eslint-fix
        name: eslint --fix
        entry: npx eslint --fix
        language: system
        types: [ts]
      - id: prettier-fix
        name: prettier --write
        entry: npx prettier --write
        language: system
        types: [ts]
