apiVersion: v1
kind: Secret
metadata:
  name: test-secret-not-masked
  namespace: test-secret-not-masked
data:
  foo: VGhpcyBpcyB2ZXJ5IHNlY3JldCE=
stringData:
  bar: "Psst don't tell anyone"
