/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param discountPercent 
 * @param `value` 
 * @param initial 
 */


data class GameResponseOffersInnerPrice (

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "discount_percent")
    val discountPercent: kotlin.Float? = null,

    @Json(name = "value")
    val `value`: kotlin.Float? = null,

    @Json(name = "initial")
    val initial: kotlin.Float? = null

) {


}

