/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain.client.model

import co.gamebrain.client.model.SearchResponseActiveFilterOptionsInner
import co.gamebrain.client.model.SearchResponseFilterOptionsInner
import co.gamebrain.client.model.SearchResponseResultsInner
import co.gamebrain.client.model.SearchResponseSorting
import co.gamebrain.client.model.SearchResponseSortingOptionsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sorting 
 * @param activeFilterOptions 
 * @param query 
 * @param totalResults 
 * @param limit 
 * @param offset 
 * @param results 
 * @param filterOptions 
 * @param sortingOptions 
 */


data class SearchResponse (

    @Json(name = "sorting")
    val sorting: SearchResponseSorting? = null,

    @Json(name = "active_filter_options")
    val activeFilterOptions: kotlin.collections.List<SearchResponseActiveFilterOptionsInner>? = null,

    @Json(name = "query")
    val query: kotlin.String? = null,

    @Json(name = "total_results")
    val totalResults: kotlin.Int? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "offset")
    val offset: kotlin.Int? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<SearchResponseResultsInner>? = null,

    @Json(name = "filter_options")
    val filterOptions: kotlin.collections.List<SearchResponseFilterOptionsInner>? = null,

    @Json(name = "sorting_options")
    val sortingOptions: kotlin.collections.List<SearchResponseSortingOptionsInner>? = null

) {


}

