/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing GameResponseOffersInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GameResponseOffersInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GameResponseOffersInner
        //private GameResponseOffersInner instance;

        public GameResponseOffersInnerTests()
        {
            // TODO uncomment below to create an instance of GameResponseOffersInner
            //instance = new GameResponseOffersInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GameResponseOffersInner
        /// </summary>
        [Fact]
        public void GameResponseOffersInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GameResponseOffersInner
            //Assert.IsType<GameResponseOffersInner>(instance);
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Fact]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
