/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResponseFilterOptionsInnerValuesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResponseFilterOptionsInnerValuesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResponseFilterOptionsInnerValuesInner
        //private SearchResponseFilterOptionsInnerValuesInner instance;

        public SearchResponseFilterOptionsInnerValuesInnerTests()
        {
            // TODO uncomment below to create an instance of SearchResponseFilterOptionsInnerValuesInner
            //instance = new SearchResponseFilterOptionsInnerValuesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResponseFilterOptionsInnerValuesInner
        /// </summary>
        [Fact]
        public void SearchResponseFilterOptionsInnerValuesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResponseFilterOptionsInnerValuesInner
            //Assert.IsType<SearchResponseFilterOptionsInnerValuesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
