/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing SimilarGamesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimilarGamesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimilarGamesResponse
        //private SimilarGamesResponse instance;

        public SimilarGamesResponseTests()
        {
            // TODO uncomment below to create an instance of SimilarGamesResponse
            //instance = new SimilarGamesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimilarGamesResponse
        /// </summary>
        [Fact]
        public void SimilarGamesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimilarGamesResponse
            //Assert.IsType<SimilarGamesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
