$schema: "https://moonrepo.dev/schemas/tasks.json"

fileGroups:
  assets:
    - assets/**/*
  sources:
    - src/**/*
  tsup-config:
    - tsup.config.ts
  tsup-dist:
    - ./target/tsup/dist/**/*

tasks:
  tsup-tsc:
    toolchain: node
    script: |
      tsc --build
    inputs:
      - "@group(assets)"
      - "@group(sources)"
      - "@group(tsup-config)"
    # outputs:
    #   - "@group(tsup-dist)"
  tsup-build:
    toolchain: node
    options:
      runDepsInParallel: false
    deps:
      - tsup-tsc
    script: |
      tsup
    inputs:
      - "@group(assets)"
      - "@group(sources)"
      - "@group(tsup-config)"
      - /packages/*/src/**/*
    outputs:
      - "@group(tsup-dist)"
