/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing GameResponseOfficialStoresInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GameResponseOfficialStoresInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GameResponseOfficialStoresInner
        //private GameResponseOfficialStoresInner instance;

        public GameResponseOfficialStoresInnerTests()
        {
            // TODO uncomment below to create an instance of GameResponseOfficialStoresInner
            //instance = new GameResponseOfficialStoresInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GameResponseOfficialStoresInner
        /// </summary>
        [Fact]
        public void GameResponseOfficialStoresInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GameResponseOfficialStoresInner
            //Assert.IsType<GameResponseOfficialStoresInner>(instance);
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
