/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing GameResponsePlatformsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GameResponsePlatformsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GameResponsePlatformsInner
        //private GameResponsePlatformsInner instance;

        public GameResponsePlatformsInnerTests()
        {
            // TODO uncomment below to create an instance of GameResponsePlatformsInner
            //instance = new GameResponsePlatformsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GameResponsePlatformsInner
        /// </summary>
        [Fact]
        public void GameResponsePlatformsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GameResponsePlatformsInner
            //Assert.IsType<GameResponsePlatformsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
