/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResponseSortingOptionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResponseSortingOptionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResponseSortingOptionsInner
        //private SearchResponseSortingOptionsInner instance;

        public SearchResponseSortingOptionsInnerTests()
        {
            // TODO uncomment below to create an instance of SearchResponseSortingOptionsInner
            //instance = new SearchResponseSortingOptionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResponseSortingOptionsInner
        /// </summary>
        [Fact]
        public void SearchResponseSortingOptionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResponseSortingOptionsInner
            //Assert.IsType<SearchResponseSortingOptionsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
    }
}
