/*
 * GameBrain API
 *
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: mail@gamebrain.co
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gamebrain.Model;
using gamebrain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gamebrain.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResponseActiveFilterOptionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResponseActiveFilterOptionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResponseActiveFilterOptionsInner
        //private SearchResponseActiveFilterOptionsInner instance;

        public SearchResponseActiveFilterOptionsInnerTests()
        {
            // TODO uncomment below to create an instance of SearchResponseActiveFilterOptionsInner
            //instance = new SearchResponseActiveFilterOptionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResponseActiveFilterOptionsInner
        /// </summary>
        [Fact]
        public void SearchResponseActiveFilterOptionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResponseActiveFilterOptionsInner
            //Assert.IsType<SearchResponseActiveFilterOptionsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Connection'
        /// </summary>
        [Fact]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
