[project]
name = "alation-ai-agent-sdk"
version = "1.0.0rc3"
description = "Alation Agent SDK"
authors = [
  { name="Jagannath (Jags) Saragadam", email="jags.saragadam@alation.com"},
  { name="Lucy Eun", email="lucy.eun@alation.com"},
  { name="Ashwin Kumar Muruganandam", email="ashwin-kumar.muruganandam@alation.com"},
  { name="Adam Talmadge", email="adam.talmadge@alation.com"},
]
maintainers = [
  { name="Jagannath (Jags) Saragadam", email="jags.saragadam@alation.com"},
  { name="Lucy Eun", email="lucy.eun@alation.com"},
  { name="Ashwin Kumar Muruganandam", email="ashwin-kumar.muruganandam@alation.com"},
  { name="Adam Talmadge", email="adam.talmadge@alation.com"},
]
dependencies = [
  "requests~=2.32.0",
  "typing_extensions~=4.15.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["alation_ai_agent_sdk/"]

[tool.pdm.scripts]
test = "pytest tests/"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.8",
]

[project.urls]
Homepage = "https://github.com/Alation/alation-ai-agent-sdk/tree/main/python/core-sdk"
Issues = "https://github.com/Alation/alation-ai-agent-sdk/issues"
Documentation = "https://github.com/Alation/alation-ai-agent-sdk/blob/main/python/core-sdk/README.md"
