/*
GameBrain API

GameBrain API

API version: 1.0.1
Contact: mail@gamebrain.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gamebrain

import (
	"encoding/json"
)

// checks if the SearchResponseActiveFilterOptionsInnerValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchResponseActiveFilterOptionsInnerValuesInner{}

// SearchResponseActiveFilterOptionsInnerValuesInner struct for SearchResponseActiveFilterOptionsInnerValuesInner
type SearchResponseActiveFilterOptionsInnerValuesInner struct {
	Match *string `json:"match,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewSearchResponseActiveFilterOptionsInnerValuesInner instantiates a new SearchResponseActiveFilterOptionsInnerValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchResponseActiveFilterOptionsInnerValuesInner() *SearchResponseActiveFilterOptionsInnerValuesInner {
	this := SearchResponseActiveFilterOptionsInnerValuesInner{}
	return &this
}

// NewSearchResponseActiveFilterOptionsInnerValuesInnerWithDefaults instantiates a new SearchResponseActiveFilterOptionsInnerValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchResponseActiveFilterOptionsInnerValuesInnerWithDefaults() *SearchResponseActiveFilterOptionsInnerValuesInner {
	this := SearchResponseActiveFilterOptionsInnerValuesInner{}
	return &this
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) GetMatch() string {
	if o == nil || IsNil(o.Match) {
		var ret string
		return ret
	}
	return *o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) GetMatchOk() (*string, bool) {
	if o == nil || IsNil(o.Match) {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) HasMatch() bool {
	if o != nil && !IsNil(o.Match) {
		return true
	}

	return false
}

// SetMatch gets a reference to the given string and assigns it to the Match field.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) SetMatch(v string) {
	o.Match = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SearchResponseActiveFilterOptionsInnerValuesInner) SetValue(v string) {
	o.Value = &v
}

func (o SearchResponseActiveFilterOptionsInnerValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchResponseActiveFilterOptionsInnerValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Match) {
		toSerialize["match"] = o.Match
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSearchResponseActiveFilterOptionsInnerValuesInner struct {
	value *SearchResponseActiveFilterOptionsInnerValuesInner
	isSet bool
}

func (v NullableSearchResponseActiveFilterOptionsInnerValuesInner) Get() *SearchResponseActiveFilterOptionsInnerValuesInner {
	return v.value
}

func (v *NullableSearchResponseActiveFilterOptionsInnerValuesInner) Set(val *SearchResponseActiveFilterOptionsInnerValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchResponseActiveFilterOptionsInnerValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchResponseActiveFilterOptionsInnerValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchResponseActiveFilterOptionsInnerValuesInner(val *SearchResponseActiveFilterOptionsInnerValuesInner) *NullableSearchResponseActiveFilterOptionsInnerValuesInner {
	return &NullableSearchResponseActiveFilterOptionsInnerValuesInner{value: val, isSet: true}
}

func (v NullableSearchResponseActiveFilterOptionsInnerValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchResponseActiveFilterOptionsInnerValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


