[project]
name = "unichat-mcp-server"
version = "0.2.19"
description = "Unichat MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [ "mcp>=1.0.0","unichat~=3.6.0"]
[[project.authors]]
name = "Stefan"
email = "shear.0-corned@icloud.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
unichat-mcp-server = "unichat_mcp_server:main"
