"""Backward-compat shim — import from pagemap.server.mcp_advanced instead."""

from pagemap.server.mcp_advanced import (  # noqa: F401
    TOOL_OUTPUT_SCHEMAS,
    BatchGetPageMapResult,
    BatchPageMapEntry,
    ChangeDetails,
    ChangeType,
    DialogInfo,
    ExecuteActionResult,
    FillFormResult,
    FormFieldResult,
    GetPageMapResult,
    GetPageStateResult,
    NavigateBackResult,
    NavigationHint,
    PageMetadata,
    ScrollPageResult,
    TaskSupportConfig,
    ToolError,
    WaitForResult,
    get_output_schema,
)

__all__ = [
    "BatchGetPageMapResult",
    "BatchPageMapEntry",
    "ChangeDetails",
    "ChangeType",
    "DialogInfo",
    "ExecuteActionResult",
    "FillFormResult",
    "FormFieldResult",
    "GetPageMapResult",
    "GetPageStateResult",
    "NavigateBackResult",
    "NavigationHint",
    "PageMetadata",
    "ScrollPageResult",
    "TOOL_OUTPUT_SCHEMAS",
    "TaskSupportConfig",
    "ToolError",
    "WaitForResult",
    "get_output_schema",
]
