"""Backward-compat shim — import from pagemap.core.page_map_builder instead."""

from pagemap.core.page_map_builder import (  # noqa: F401
    _CJK_TOKEN_MULTIPLIERS,
    _DOM_GUARD_AND_HIDDEN_JS,
    _MIN_INTERACTABLE_BUDGET,
    _OVERHEAD_TOKEN_ESTIMATE,
    DEFAULT_PRUNED_CONTEXT_TOKENS,
    DEFAULT_TOTAL_BUDGET_TOKENS,
    DOMAIN_SCHEMA_MAP,
    MAX_DOM_NODES,
    MAX_HTML_SIZE_BYTES,
    TokenBudget,
    _budget_filter_interactables,
    _build_navigation_hints,
    _check_blocked_page,
    _check_html_size,
    _check_resource_limits,
    _detect_all_safe,
    _detect_schema_from_jsonld,
    _extract_interactables_from_html,
    _merge_structured_images,
    _resolve_jsonld_type,
    _sample_visible_text,
    build_page_map_from_page,
    build_page_map_from_snapshot,
    build_page_map_live,
    build_page_map_offline,
    compute_token_budget,
    detect_page_type,
    detect_schema,
    rebuild_content_only,
    rebuild_interactables_only,
)

__all__ = [
    "DEFAULT_PRUNED_CONTEXT_TOKENS",
    "DEFAULT_TOTAL_BUDGET_TOKENS",
    "DOMAIN_SCHEMA_MAP",
    "MAX_DOM_NODES",
    "MAX_HTML_SIZE_BYTES",
    "TokenBudget",
    "build_page_map_from_page",
    "build_page_map_from_snapshot",
    "build_page_map_live",
    "build_page_map_offline",
    "compute_token_budget",
    "detect_page_type",
    "detect_schema",
    "rebuild_content_only",
    "rebuild_interactables_only",
]
