kind: Task
metadata:
  labels:
    suite: kiali
  name: "Get service detail"
  category: "Resource Inspection"
  difficulty: easy
steps:
  setup:
    inline: |-
      #!/usr/bin/env bash
  verify:
    contains: "health status"
  cleanup:
    inline: |-
      #!/usr/bin/env bash          
  prompt:
    inline: Get the full details for the service reviews in the namespace bookinfo.