{-
   GameBrain API

   GameBrain API

   OpenAPI Version: 3.0.0
   GameBrain API API version: 1.0.1
   Contact: mail@gamebrain.co
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : GameBrain.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module GameBrain.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import GameBrain.Model
import GameBrain.Core


-- * GameNewsItem

-- | 'gameNewsItemTitle' Lens
gameNewsItemTitleL :: Lens_' GameNewsItem (Text)
gameNewsItemTitleL f GameNewsItem{..} = (\gameNewsItemTitle -> GameNewsItem { gameNewsItemTitle, ..} ) <$> f gameNewsItemTitle
{-# INLINE gameNewsItemTitleL #-}

-- | 'gameNewsItemUrl' Lens
gameNewsItemUrlL :: Lens_' GameNewsItem (Text)
gameNewsItemUrlL f GameNewsItem{..} = (\gameNewsItemUrl -> GameNewsItem { gameNewsItemUrl, ..} ) <$> f gameNewsItemUrl
{-# INLINE gameNewsItemUrlL #-}

-- | 'gameNewsItemSource' Lens
gameNewsItemSourceL :: Lens_' GameNewsItem (Text)
gameNewsItemSourceL f GameNewsItem{..} = (\gameNewsItemSource -> GameNewsItem { gameNewsItemSource, ..} ) <$> f gameNewsItemSource
{-# INLINE gameNewsItemSourceL #-}

-- | 'gameNewsItemImage' Lens
gameNewsItemImageL :: Lens_' GameNewsItem (Maybe Text)
gameNewsItemImageL f GameNewsItem{..} = (\gameNewsItemImage -> GameNewsItem { gameNewsItemImage, ..} ) <$> f gameNewsItemImage
{-# INLINE gameNewsItemImageL #-}

-- | 'gameNewsItemPublished' Lens
gameNewsItemPublishedL :: Lens_' GameNewsItem (Date)
gameNewsItemPublishedL f GameNewsItem{..} = (\gameNewsItemPublished -> GameNewsItem { gameNewsItemPublished, ..} ) <$> f gameNewsItemPublished
{-# INLINE gameNewsItemPublishedL #-}



-- * GameNewsResponse

-- | 'gameNewsResponseNews' Lens
gameNewsResponseNewsL :: Lens_' GameNewsResponse ([GameNewsItem])
gameNewsResponseNewsL f GameNewsResponse{..} = (\gameNewsResponseNews -> GameNewsResponse { gameNewsResponseNews, ..} ) <$> f gameNewsResponseNews
{-# INLINE gameNewsResponseNewsL #-}



-- * GameResponse

-- | 'gameResponseId' Lens
gameResponseIdL :: Lens_' GameResponse (Maybe Int)
gameResponseIdL f GameResponse{..} = (\gameResponseId -> GameResponse { gameResponseId, ..} ) <$> f gameResponseId
{-# INLINE gameResponseIdL #-}

-- | 'gameResponseName' Lens
gameResponseNameL :: Lens_' GameResponse (Maybe Text)
gameResponseNameL f GameResponse{..} = (\gameResponseName -> GameResponse { gameResponseName, ..} ) <$> f gameResponseName
{-# INLINE gameResponseNameL #-}

-- | 'gameResponseImage' Lens
gameResponseImageL :: Lens_' GameResponse (Maybe Text)
gameResponseImageL f GameResponse{..} = (\gameResponseImage -> GameResponse { gameResponseImage, ..} ) <$> f gameResponseImage
{-# INLINE gameResponseImageL #-}

-- | 'gameResponseGameplay' Lens
gameResponseGameplayL :: Lens_' GameResponse (Maybe Text)
gameResponseGameplayL f GameResponse{..} = (\gameResponseGameplay -> GameResponse { gameResponseGameplay, ..} ) <$> f gameResponseGameplay
{-# INLINE gameResponseGameplayL #-}

-- | 'gameResponseLink' Lens
gameResponseLinkL :: Lens_' GameResponse (Maybe Text)
gameResponseLinkL f GameResponse{..} = (\gameResponseLink -> GameResponse { gameResponseLink, ..} ) <$> f gameResponseLink
{-# INLINE gameResponseLinkL #-}

-- | 'gameResponseXUrl' Lens
gameResponseXUrlL :: Lens_' GameResponse (Maybe Text)
gameResponseXUrlL f GameResponse{..} = (\gameResponseXUrl -> GameResponse { gameResponseXUrl, ..} ) <$> f gameResponseXUrl
{-# INLINE gameResponseXUrlL #-}

-- | 'gameResponseRating' Lens
gameResponseRatingL :: Lens_' GameResponse (Maybe GameResponseRating)
gameResponseRatingL f GameResponse{..} = (\gameResponseRating -> GameResponse { gameResponseRating, ..} ) <$> f gameResponseRating
{-# INLINE gameResponseRatingL #-}

-- | 'gameResponseDescription' Lens
gameResponseDescriptionL :: Lens_' GameResponse (Maybe Text)
gameResponseDescriptionL f GameResponse{..} = (\gameResponseDescription -> GameResponse { gameResponseDescription, ..} ) <$> f gameResponseDescription
{-# INLINE gameResponseDescriptionL #-}

-- | 'gameResponseShortDescription' Lens
gameResponseShortDescriptionL :: Lens_' GameResponse (Maybe Text)
gameResponseShortDescriptionL f GameResponse{..} = (\gameResponseShortDescription -> GameResponse { gameResponseShortDescription, ..} ) <$> f gameResponseShortDescription
{-# INLINE gameResponseShortDescriptionL #-}

-- | 'gameResponseReleaseDate' Lens
gameResponseReleaseDateL :: Lens_' GameResponse (Maybe Date)
gameResponseReleaseDateL f GameResponse{..} = (\gameResponseReleaseDate -> GameResponse { gameResponseReleaseDate, ..} ) <$> f gameResponseReleaseDate
{-# INLINE gameResponseReleaseDateL #-}

-- | 'gameResponseDeveloper' Lens
gameResponseDeveloperL :: Lens_' GameResponse (Maybe Text)
gameResponseDeveloperL f GameResponse{..} = (\gameResponseDeveloper -> GameResponse { gameResponseDeveloper, ..} ) <$> f gameResponseDeveloper
{-# INLINE gameResponseDeveloperL #-}

-- | 'gameResponsePlaytime' Lens
gameResponsePlaytimeL :: Lens_' GameResponse (Maybe GameResponsePlaytime)
gameResponsePlaytimeL f GameResponse{..} = (\gameResponsePlaytime -> GameResponse { gameResponsePlaytime, ..} ) <$> f gameResponsePlaytime
{-# INLINE gameResponsePlaytimeL #-}

-- | 'gameResponsePlatforms' Lens
gameResponsePlatformsL :: Lens_' GameResponse (Maybe [GameResponsePlatformsInner])
gameResponsePlatformsL f GameResponse{..} = (\gameResponsePlatforms -> GameResponse { gameResponsePlatforms, ..} ) <$> f gameResponsePlatforms
{-# INLINE gameResponsePlatformsL #-}

-- | 'gameResponseTags' Lens
gameResponseTagsL :: Lens_' GameResponse (Maybe [Text])
gameResponseTagsL f GameResponse{..} = (\gameResponseTags -> GameResponse { gameResponseTags, ..} ) <$> f gameResponseTags
{-# INLINE gameResponseTagsL #-}

-- | 'gameResponseGenres' Lens
gameResponseGenresL :: Lens_' GameResponse (Maybe [GameResponsePlatformsInner])
gameResponseGenresL f GameResponse{..} = (\gameResponseGenres -> GameResponse { gameResponseGenres, ..} ) <$> f gameResponseGenres
{-# INLINE gameResponseGenresL #-}

-- | 'gameResponseGenre' Lens
gameResponseGenreL :: Lens_' GameResponse (Maybe Text)
gameResponseGenreL f GameResponse{..} = (\gameResponseGenre -> GameResponse { gameResponseGenre, ..} ) <$> f gameResponseGenre
{-# INLINE gameResponseGenreL #-}

-- | 'gameResponseThemes' Lens
gameResponseThemesL :: Lens_' GameResponse (Maybe [GameResponsePlatformsInner])
gameResponseThemesL f GameResponse{..} = (\gameResponseThemes -> GameResponse { gameResponseThemes, ..} ) <$> f gameResponseThemes
{-# INLINE gameResponseThemesL #-}

-- | 'gameResponseAdultOnly' Lens
gameResponseAdultOnlyL :: Lens_' GameResponse (Maybe Bool)
gameResponseAdultOnlyL f GameResponse{..} = (\gameResponseAdultOnly -> GameResponse { gameResponseAdultOnly, ..} ) <$> f gameResponseAdultOnly
{-# INLINE gameResponseAdultOnlyL #-}

-- | 'gameResponsePlayModes' Lens
gameResponsePlayModesL :: Lens_' GameResponse (Maybe [GameResponsePlatformsInner])
gameResponsePlayModesL f GameResponse{..} = (\gameResponsePlayModes -> GameResponse { gameResponsePlayModes, ..} ) <$> f gameResponsePlayModes
{-# INLINE gameResponsePlayModesL #-}

-- | 'gameResponseScreenshots' Lens
gameResponseScreenshotsL :: Lens_' GameResponse (Maybe [Text])
gameResponseScreenshotsL f GameResponse{..} = (\gameResponseScreenshots -> GameResponse { gameResponseScreenshots, ..} ) <$> f gameResponseScreenshots
{-# INLINE gameResponseScreenshotsL #-}

-- | 'gameResponseVideos' Lens
gameResponseVideosL :: Lens_' GameResponse (Maybe [Text])
gameResponseVideosL f GameResponse{..} = (\gameResponseVideos -> GameResponse { gameResponseVideos, ..} ) <$> f gameResponseVideos
{-# INLINE gameResponseVideosL #-}

-- | 'gameResponseOffers' Lens
gameResponseOffersL :: Lens_' GameResponse (Maybe [GameResponseOffersInner])
gameResponseOffersL f GameResponse{..} = (\gameResponseOffers -> GameResponse { gameResponseOffers, ..} ) <$> f gameResponseOffers
{-# INLINE gameResponseOffersL #-}

-- | 'gameResponseOfficialStores' Lens
gameResponseOfficialStoresL :: Lens_' GameResponse (Maybe [GameResponseOfficialStoresInner])
gameResponseOfficialStoresL f GameResponse{..} = (\gameResponseOfficialStores -> GameResponse { gameResponseOfficialStores, ..} ) <$> f gameResponseOfficialStores
{-# INLINE gameResponseOfficialStoresL #-}

-- | 'gameResponseMicroTrailer' Lens
gameResponseMicroTrailerL :: Lens_' GameResponse (Maybe Text)
gameResponseMicroTrailerL f GameResponse{..} = (\gameResponseMicroTrailer -> GameResponse { gameResponseMicroTrailer, ..} ) <$> f gameResponseMicroTrailer
{-# INLINE gameResponseMicroTrailerL #-}



-- * GameResponseOffersInner

-- | 'gameResponseOffersInnerPrice' Lens
gameResponseOffersInnerPriceL :: Lens_' GameResponseOffersInner (Maybe GameResponseOffersInnerPrice)
gameResponseOffersInnerPriceL f GameResponseOffersInner{..} = (\gameResponseOffersInnerPrice -> GameResponseOffersInner { gameResponseOffersInnerPrice, ..} ) <$> f gameResponseOffersInnerPrice
{-# INLINE gameResponseOffersInnerPriceL #-}

-- | 'gameResponseOffersInnerStoreName' Lens
gameResponseOffersInnerStoreNameL :: Lens_' GameResponseOffersInner (Maybe Text)
gameResponseOffersInnerStoreNameL f GameResponseOffersInner{..} = (\gameResponseOffersInnerStoreName -> GameResponseOffersInner { gameResponseOffersInnerStoreName, ..} ) <$> f gameResponseOffersInnerStoreName
{-# INLINE gameResponseOffersInnerStoreNameL #-}

-- | 'gameResponseOffersInnerPlatform' Lens
gameResponseOffersInnerPlatformL :: Lens_' GameResponseOffersInner (Maybe Text)
gameResponseOffersInnerPlatformL f GameResponseOffersInner{..} = (\gameResponseOffersInnerPlatform -> GameResponseOffersInner { gameResponseOffersInnerPlatform, ..} ) <$> f gameResponseOffersInnerPlatform
{-# INLINE gameResponseOffersInnerPlatformL #-}

-- | 'gameResponseOffersInnerTitle' Lens
gameResponseOffersInnerTitleL :: Lens_' GameResponseOffersInner (Maybe Text)
gameResponseOffersInnerTitleL f GameResponseOffersInner{..} = (\gameResponseOffersInnerTitle -> GameResponseOffersInner { gameResponseOffersInnerTitle, ..} ) <$> f gameResponseOffersInnerTitle
{-# INLINE gameResponseOffersInnerTitleL #-}

-- | 'gameResponseOffersInnerUrl' Lens
gameResponseOffersInnerUrlL :: Lens_' GameResponseOffersInner (Maybe Text)
gameResponseOffersInnerUrlL f GameResponseOffersInner{..} = (\gameResponseOffersInnerUrl -> GameResponseOffersInner { gameResponseOffersInnerUrl, ..} ) <$> f gameResponseOffersInnerUrl
{-# INLINE gameResponseOffersInnerUrlL #-}



-- * GameResponseOffersInnerPrice

-- | 'gameResponseOffersInnerPriceCurrency' Lens
gameResponseOffersInnerPriceCurrencyL :: Lens_' GameResponseOffersInnerPrice (Maybe Text)
gameResponseOffersInnerPriceCurrencyL f GameResponseOffersInnerPrice{..} = (\gameResponseOffersInnerPriceCurrency -> GameResponseOffersInnerPrice { gameResponseOffersInnerPriceCurrency, ..} ) <$> f gameResponseOffersInnerPriceCurrency
{-# INLINE gameResponseOffersInnerPriceCurrencyL #-}

-- | 'gameResponseOffersInnerPriceDiscountPercent' Lens
gameResponseOffersInnerPriceDiscountPercentL :: Lens_' GameResponseOffersInnerPrice (Maybe Float)
gameResponseOffersInnerPriceDiscountPercentL f GameResponseOffersInnerPrice{..} = (\gameResponseOffersInnerPriceDiscountPercent -> GameResponseOffersInnerPrice { gameResponseOffersInnerPriceDiscountPercent, ..} ) <$> f gameResponseOffersInnerPriceDiscountPercent
{-# INLINE gameResponseOffersInnerPriceDiscountPercentL #-}

-- | 'gameResponseOffersInnerPriceValue' Lens
gameResponseOffersInnerPriceValueL :: Lens_' GameResponseOffersInnerPrice (Maybe Float)
gameResponseOffersInnerPriceValueL f GameResponseOffersInnerPrice{..} = (\gameResponseOffersInnerPriceValue -> GameResponseOffersInnerPrice { gameResponseOffersInnerPriceValue, ..} ) <$> f gameResponseOffersInnerPriceValue
{-# INLINE gameResponseOffersInnerPriceValueL #-}

-- | 'gameResponseOffersInnerPriceInitial' Lens
gameResponseOffersInnerPriceInitialL :: Lens_' GameResponseOffersInnerPrice (Maybe Float)
gameResponseOffersInnerPriceInitialL f GameResponseOffersInnerPrice{..} = (\gameResponseOffersInnerPriceInitial -> GameResponseOffersInnerPrice { gameResponseOffersInnerPriceInitial, ..} ) <$> f gameResponseOffersInnerPriceInitial
{-# INLINE gameResponseOffersInnerPriceInitialL #-}



-- * GameResponseOfficialStoresInner

-- | 'gameResponseOfficialStoresInnerSource' Lens
gameResponseOfficialStoresInnerSourceL :: Lens_' GameResponseOfficialStoresInner (Maybe Text)
gameResponseOfficialStoresInnerSourceL f GameResponseOfficialStoresInner{..} = (\gameResponseOfficialStoresInnerSource -> GameResponseOfficialStoresInner { gameResponseOfficialStoresInnerSource, ..} ) <$> f gameResponseOfficialStoresInnerSource
{-# INLINE gameResponseOfficialStoresInnerSourceL #-}

-- | 'gameResponseOfficialStoresInnerUrl' Lens
gameResponseOfficialStoresInnerUrlL :: Lens_' GameResponseOfficialStoresInner (Maybe Text)
gameResponseOfficialStoresInnerUrlL f GameResponseOfficialStoresInner{..} = (\gameResponseOfficialStoresInnerUrl -> GameResponseOfficialStoresInner { gameResponseOfficialStoresInnerUrl, ..} ) <$> f gameResponseOfficialStoresInnerUrl
{-# INLINE gameResponseOfficialStoresInnerUrlL #-}



-- * GameResponsePlatformsInner

-- | 'gameResponsePlatformsInnerValue' Lens
gameResponsePlatformsInnerValueL :: Lens_' GameResponsePlatformsInner (Maybe Text)
gameResponsePlatformsInnerValueL f GameResponsePlatformsInner{..} = (\gameResponsePlatformsInnerValue -> GameResponsePlatformsInner { gameResponsePlatformsInnerValue, ..} ) <$> f gameResponsePlatformsInnerValue
{-# INLINE gameResponsePlatformsInnerValueL #-}

-- | 'gameResponsePlatformsInnerName' Lens
gameResponsePlatformsInnerNameL :: Lens_' GameResponsePlatformsInner (Maybe Text)
gameResponsePlatformsInnerNameL f GameResponsePlatformsInner{..} = (\gameResponsePlatformsInnerName -> GameResponsePlatformsInner { gameResponsePlatformsInnerName, ..} ) <$> f gameResponsePlatformsInnerName
{-# INLINE gameResponsePlatformsInnerNameL #-}



-- * GameResponsePlaytime

-- | 'gameResponsePlaytimePercentiles' Lens
gameResponsePlaytimePercentilesL :: Lens_' GameResponsePlaytime (Maybe [Int])
gameResponsePlaytimePercentilesL f GameResponsePlaytime{..} = (\gameResponsePlaytimePercentiles -> GameResponsePlaytime { gameResponsePlaytimePercentiles, ..} ) <$> f gameResponsePlaytimePercentiles
{-# INLINE gameResponsePlaytimePercentilesL #-}

-- | 'gameResponsePlaytimeMin' Lens
gameResponsePlaytimeMinL :: Lens_' GameResponsePlaytime (Maybe Int)
gameResponsePlaytimeMinL f GameResponsePlaytime{..} = (\gameResponsePlaytimeMin -> GameResponsePlaytime { gameResponsePlaytimeMin, ..} ) <$> f gameResponsePlaytimeMin
{-# INLINE gameResponsePlaytimeMinL #-}

-- | 'gameResponsePlaytimeMedian' Lens
gameResponsePlaytimeMedianL :: Lens_' GameResponsePlaytime (Maybe Int)
gameResponsePlaytimeMedianL f GameResponsePlaytime{..} = (\gameResponsePlaytimeMedian -> GameResponsePlaytime { gameResponsePlaytimeMedian, ..} ) <$> f gameResponsePlaytimeMedian
{-# INLINE gameResponsePlaytimeMedianL #-}

-- | 'gameResponsePlaytimeMax' Lens
gameResponsePlaytimeMaxL :: Lens_' GameResponsePlaytime (Maybe Int)
gameResponsePlaytimeMaxL f GameResponsePlaytime{..} = (\gameResponsePlaytimeMax -> GameResponsePlaytime { gameResponsePlaytimeMax, ..} ) <$> f gameResponsePlaytimeMax
{-# INLINE gameResponsePlaytimeMaxL #-}

-- | 'gameResponsePlaytimeMean' Lens
gameResponsePlaytimeMeanL :: Lens_' GameResponsePlaytime (Maybe Float)
gameResponsePlaytimeMeanL f GameResponsePlaytime{..} = (\gameResponsePlaytimeMean -> GameResponsePlaytime { gameResponsePlaytimeMean, ..} ) <$> f gameResponsePlaytimeMean
{-# INLINE gameResponsePlaytimeMeanL #-}

-- | 'gameResponsePlaytimeMentions' Lens
gameResponsePlaytimeMentionsL :: Lens_' GameResponsePlaytime (Maybe Int)
gameResponsePlaytimeMentionsL f GameResponsePlaytime{..} = (\gameResponsePlaytimeMentions -> GameResponsePlaytime { gameResponsePlaytimeMentions, ..} ) <$> f gameResponsePlaytimeMentions
{-# INLINE gameResponsePlaytimeMentionsL #-}



-- * GameResponseRating

-- | 'gameResponseRatingMean' Lens
gameResponseRatingMeanL :: Lens_' GameResponseRating (Maybe Float)
gameResponseRatingMeanL f GameResponseRating{..} = (\gameResponseRatingMean -> GameResponseRating { gameResponseRatingMean, ..} ) <$> f gameResponseRatingMean
{-# INLINE gameResponseRatingMeanL #-}

-- | 'gameResponseRatingCount' Lens
gameResponseRatingCountL :: Lens_' GameResponseRating (Maybe Int)
gameResponseRatingCountL f GameResponseRating{..} = (\gameResponseRatingCount -> GameResponseRating { gameResponseRatingCount, ..} ) <$> f gameResponseRatingCount
{-# INLINE gameResponseRatingCountL #-}

-- | 'gameResponseRatingMeanPlayers' Lens
gameResponseRatingMeanPlayersL :: Lens_' GameResponseRating (Maybe Float)
gameResponseRatingMeanPlayersL f GameResponseRating{..} = (\gameResponseRatingMeanPlayers -> GameResponseRating { gameResponseRatingMeanPlayers, ..} ) <$> f gameResponseRatingMeanPlayers
{-# INLINE gameResponseRatingMeanPlayersL #-}

-- | 'gameResponseRatingCountPlayers' Lens
gameResponseRatingCountPlayersL :: Lens_' GameResponseRating (Maybe Int)
gameResponseRatingCountPlayersL f GameResponseRating{..} = (\gameResponseRatingCountPlayers -> GameResponseRating { gameResponseRatingCountPlayers, ..} ) <$> f gameResponseRatingCountPlayers
{-# INLINE gameResponseRatingCountPlayersL #-}

-- | 'gameResponseRatingMeanCritics' Lens
gameResponseRatingMeanCriticsL :: Lens_' GameResponseRating (Maybe Float)
gameResponseRatingMeanCriticsL f GameResponseRating{..} = (\gameResponseRatingMeanCritics -> GameResponseRating { gameResponseRatingMeanCritics, ..} ) <$> f gameResponseRatingMeanCritics
{-# INLINE gameResponseRatingMeanCriticsL #-}

-- | 'gameResponseRatingCountCritics' Lens
gameResponseRatingCountCriticsL :: Lens_' GameResponseRating (Maybe Int)
gameResponseRatingCountCriticsL f GameResponseRating{..} = (\gameResponseRatingCountCritics -> GameResponseRating { gameResponseRatingCountCritics, ..} ) <$> f gameResponseRatingCountCritics
{-# INLINE gameResponseRatingCountCriticsL #-}



-- * SearchResponse

-- | 'searchResponseSorting' Lens
searchResponseSortingL :: Lens_' SearchResponse (Maybe SearchResponseSorting)
searchResponseSortingL f SearchResponse{..} = (\searchResponseSorting -> SearchResponse { searchResponseSorting, ..} ) <$> f searchResponseSorting
{-# INLINE searchResponseSortingL #-}

-- | 'searchResponseActiveFilterOptions' Lens
searchResponseActiveFilterOptionsL :: Lens_' SearchResponse (Maybe [SearchResponseActiveFilterOptionsInner])
searchResponseActiveFilterOptionsL f SearchResponse{..} = (\searchResponseActiveFilterOptions -> SearchResponse { searchResponseActiveFilterOptions, ..} ) <$> f searchResponseActiveFilterOptions
{-# INLINE searchResponseActiveFilterOptionsL #-}

-- | 'searchResponseQuery' Lens
searchResponseQueryL :: Lens_' SearchResponse (Maybe Text)
searchResponseQueryL f SearchResponse{..} = (\searchResponseQuery -> SearchResponse { searchResponseQuery, ..} ) <$> f searchResponseQuery
{-# INLINE searchResponseQueryL #-}

-- | 'searchResponseTotalResults' Lens
searchResponseTotalResultsL :: Lens_' SearchResponse (Maybe Int)
searchResponseTotalResultsL f SearchResponse{..} = (\searchResponseTotalResults -> SearchResponse { searchResponseTotalResults, ..} ) <$> f searchResponseTotalResults
{-# INLINE searchResponseTotalResultsL #-}

-- | 'searchResponseLimit' Lens
searchResponseLimitL :: Lens_' SearchResponse (Maybe Int)
searchResponseLimitL f SearchResponse{..} = (\searchResponseLimit -> SearchResponse { searchResponseLimit, ..} ) <$> f searchResponseLimit
{-# INLINE searchResponseLimitL #-}

-- | 'searchResponseOffset' Lens
searchResponseOffsetL :: Lens_' SearchResponse (Maybe Int)
searchResponseOffsetL f SearchResponse{..} = (\searchResponseOffset -> SearchResponse { searchResponseOffset, ..} ) <$> f searchResponseOffset
{-# INLINE searchResponseOffsetL #-}

-- | 'searchResponseResults' Lens
searchResponseResultsL :: Lens_' SearchResponse (Maybe [SearchResponseResultsInner])
searchResponseResultsL f SearchResponse{..} = (\searchResponseResults -> SearchResponse { searchResponseResults, ..} ) <$> f searchResponseResults
{-# INLINE searchResponseResultsL #-}

-- | 'searchResponseFilterOptions' Lens
searchResponseFilterOptionsL :: Lens_' SearchResponse (Maybe [SearchResponseFilterOptionsInner])
searchResponseFilterOptionsL f SearchResponse{..} = (\searchResponseFilterOptions -> SearchResponse { searchResponseFilterOptions, ..} ) <$> f searchResponseFilterOptions
{-# INLINE searchResponseFilterOptionsL #-}

-- | 'searchResponseSortingOptions' Lens
searchResponseSortingOptionsL :: Lens_' SearchResponse (Maybe [SearchResponseSortingOptionsInner])
searchResponseSortingOptionsL f SearchResponse{..} = (\searchResponseSortingOptions -> SearchResponse { searchResponseSortingOptions, ..} ) <$> f searchResponseSortingOptions
{-# INLINE searchResponseSortingOptionsL #-}



-- * SearchResponseActiveFilterOptionsInner

-- | 'searchResponseActiveFilterOptionsInnerKey' Lens
searchResponseActiveFilterOptionsInnerKeyL :: Lens_' SearchResponseActiveFilterOptionsInner (Maybe Text)
searchResponseActiveFilterOptionsInnerKeyL f SearchResponseActiveFilterOptionsInner{..} = (\searchResponseActiveFilterOptionsInnerKey -> SearchResponseActiveFilterOptionsInner { searchResponseActiveFilterOptionsInnerKey, ..} ) <$> f searchResponseActiveFilterOptionsInnerKey
{-# INLINE searchResponseActiveFilterOptionsInnerKeyL #-}

-- | 'searchResponseActiveFilterOptionsInnerConnection' Lens
searchResponseActiveFilterOptionsInnerConnectionL :: Lens_' SearchResponseActiveFilterOptionsInner (Maybe Text)
searchResponseActiveFilterOptionsInnerConnectionL f SearchResponseActiveFilterOptionsInner{..} = (\searchResponseActiveFilterOptionsInnerConnection -> SearchResponseActiveFilterOptionsInner { searchResponseActiveFilterOptionsInnerConnection, ..} ) <$> f searchResponseActiveFilterOptionsInnerConnection
{-# INLINE searchResponseActiveFilterOptionsInnerConnectionL #-}

-- | 'searchResponseActiveFilterOptionsInnerValues' Lens
searchResponseActiveFilterOptionsInnerValuesL :: Lens_' SearchResponseActiveFilterOptionsInner (Maybe [SearchResponseActiveFilterOptionsInnerValuesInner])
searchResponseActiveFilterOptionsInnerValuesL f SearchResponseActiveFilterOptionsInner{..} = (\searchResponseActiveFilterOptionsInnerValues -> SearchResponseActiveFilterOptionsInner { searchResponseActiveFilterOptionsInnerValues, ..} ) <$> f searchResponseActiveFilterOptionsInnerValues
{-# INLINE searchResponseActiveFilterOptionsInnerValuesL #-}



-- * SearchResponseActiveFilterOptionsInnerValuesInner

-- | 'searchResponseActiveFilterOptionsInnerValuesInnerMatch' Lens
searchResponseActiveFilterOptionsInnerValuesInnerMatchL :: Lens_' SearchResponseActiveFilterOptionsInnerValuesInner (Maybe Text)
searchResponseActiveFilterOptionsInnerValuesInnerMatchL f SearchResponseActiveFilterOptionsInnerValuesInner{..} = (\searchResponseActiveFilterOptionsInnerValuesInnerMatch -> SearchResponseActiveFilterOptionsInnerValuesInner { searchResponseActiveFilterOptionsInnerValuesInnerMatch, ..} ) <$> f searchResponseActiveFilterOptionsInnerValuesInnerMatch
{-# INLINE searchResponseActiveFilterOptionsInnerValuesInnerMatchL #-}

-- | 'searchResponseActiveFilterOptionsInnerValuesInnerValue' Lens
searchResponseActiveFilterOptionsInnerValuesInnerValueL :: Lens_' SearchResponseActiveFilterOptionsInnerValuesInner (Maybe Text)
searchResponseActiveFilterOptionsInnerValuesInnerValueL f SearchResponseActiveFilterOptionsInnerValuesInner{..} = (\searchResponseActiveFilterOptionsInnerValuesInnerValue -> SearchResponseActiveFilterOptionsInnerValuesInner { searchResponseActiveFilterOptionsInnerValuesInnerValue, ..} ) <$> f searchResponseActiveFilterOptionsInnerValuesInnerValue
{-# INLINE searchResponseActiveFilterOptionsInnerValuesInnerValueL #-}



-- * SearchResponseFilterOptionsInner

-- | 'searchResponseFilterOptionsInnerName' Lens
searchResponseFilterOptionsInnerNameL :: Lens_' SearchResponseFilterOptionsInner (Maybe Text)
searchResponseFilterOptionsInnerNameL f SearchResponseFilterOptionsInner{..} = (\searchResponseFilterOptionsInnerName -> SearchResponseFilterOptionsInner { searchResponseFilterOptionsInnerName, ..} ) <$> f searchResponseFilterOptionsInnerName
{-# INLINE searchResponseFilterOptionsInnerNameL #-}

-- | 'searchResponseFilterOptionsInnerKey' Lens
searchResponseFilterOptionsInnerKeyL :: Lens_' SearchResponseFilterOptionsInner (Maybe Text)
searchResponseFilterOptionsInnerKeyL f SearchResponseFilterOptionsInner{..} = (\searchResponseFilterOptionsInnerKey -> SearchResponseFilterOptionsInner { searchResponseFilterOptionsInnerKey, ..} ) <$> f searchResponseFilterOptionsInnerKey
{-# INLINE searchResponseFilterOptionsInnerKeyL #-}

-- | 'searchResponseFilterOptionsInnerValues' Lens
searchResponseFilterOptionsInnerValuesL :: Lens_' SearchResponseFilterOptionsInner (Maybe [SearchResponseFilterOptionsInnerValuesInner])
searchResponseFilterOptionsInnerValuesL f SearchResponseFilterOptionsInner{..} = (\searchResponseFilterOptionsInnerValues -> SearchResponseFilterOptionsInner { searchResponseFilterOptionsInnerValues, ..} ) <$> f searchResponseFilterOptionsInnerValues
{-# INLINE searchResponseFilterOptionsInnerValuesL #-}



-- * SearchResponseFilterOptionsInnerValuesInner

-- | 'searchResponseFilterOptionsInnerValuesInnerName' Lens
searchResponseFilterOptionsInnerValuesInnerNameL :: Lens_' SearchResponseFilterOptionsInnerValuesInner (Maybe Text)
searchResponseFilterOptionsInnerValuesInnerNameL f SearchResponseFilterOptionsInnerValuesInner{..} = (\searchResponseFilterOptionsInnerValuesInnerName -> SearchResponseFilterOptionsInnerValuesInner { searchResponseFilterOptionsInnerValuesInnerName, ..} ) <$> f searchResponseFilterOptionsInnerValuesInnerName
{-# INLINE searchResponseFilterOptionsInnerValuesInnerNameL #-}

-- | 'searchResponseFilterOptionsInnerValuesInnerKey' Lens
searchResponseFilterOptionsInnerValuesInnerKeyL :: Lens_' SearchResponseFilterOptionsInnerValuesInner (Maybe Text)
searchResponseFilterOptionsInnerValuesInnerKeyL f SearchResponseFilterOptionsInnerValuesInner{..} = (\searchResponseFilterOptionsInnerValuesInnerKey -> SearchResponseFilterOptionsInnerValuesInner { searchResponseFilterOptionsInnerValuesInnerKey, ..} ) <$> f searchResponseFilterOptionsInnerValuesInnerKey
{-# INLINE searchResponseFilterOptionsInnerValuesInnerKeyL #-}

-- | 'searchResponseFilterOptionsInnerValuesInnerCount' Lens
searchResponseFilterOptionsInnerValuesInnerCountL :: Lens_' SearchResponseFilterOptionsInnerValuesInner (Maybe Double)
searchResponseFilterOptionsInnerValuesInnerCountL f SearchResponseFilterOptionsInnerValuesInner{..} = (\searchResponseFilterOptionsInnerValuesInnerCount -> SearchResponseFilterOptionsInnerValuesInner { searchResponseFilterOptionsInnerValuesInnerCount, ..} ) <$> f searchResponseFilterOptionsInnerValuesInnerCount
{-# INLINE searchResponseFilterOptionsInnerValuesInnerCountL #-}



-- * SearchResponseResultsInner

-- | 'searchResponseResultsInnerId' Lens
searchResponseResultsInnerIdL :: Lens_' SearchResponseResultsInner (Maybe Int)
searchResponseResultsInnerIdL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerId -> SearchResponseResultsInner { searchResponseResultsInnerId, ..} ) <$> f searchResponseResultsInnerId
{-# INLINE searchResponseResultsInnerIdL #-}

-- | 'searchResponseResultsInnerYear' Lens
searchResponseResultsInnerYearL :: Lens_' SearchResponseResultsInner (Maybe Double)
searchResponseResultsInnerYearL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerYear -> SearchResponseResultsInner { searchResponseResultsInnerYear, ..} ) <$> f searchResponseResultsInnerYear
{-# INLINE searchResponseResultsInnerYearL #-}

-- | 'searchResponseResultsInnerName' Lens
searchResponseResultsInnerNameL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerNameL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerName -> SearchResponseResultsInner { searchResponseResultsInnerName, ..} ) <$> f searchResponseResultsInnerName
{-# INLINE searchResponseResultsInnerNameL #-}

-- | 'searchResponseResultsInnerGenre' Lens
searchResponseResultsInnerGenreL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerGenreL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerGenre -> SearchResponseResultsInner { searchResponseResultsInnerGenre, ..} ) <$> f searchResponseResultsInnerGenre
{-# INLINE searchResponseResultsInnerGenreL #-}

-- | 'searchResponseResultsInnerImage' Lens
searchResponseResultsInnerImageL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerImageL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerImage -> SearchResponseResultsInner { searchResponseResultsInnerImage, ..} ) <$> f searchResponseResultsInnerImage
{-# INLINE searchResponseResultsInnerImageL #-}

-- | 'searchResponseResultsInnerLink' Lens
searchResponseResultsInnerLinkL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerLinkL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerLink -> SearchResponseResultsInner { searchResponseResultsInnerLink, ..} ) <$> f searchResponseResultsInnerLink
{-# INLINE searchResponseResultsInnerLinkL #-}

-- | 'searchResponseResultsInnerRating' Lens
searchResponseResultsInnerRatingL :: Lens_' SearchResponseResultsInner (Maybe SearchResponseResultsInnerRating)
searchResponseResultsInnerRatingL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerRating -> SearchResponseResultsInner { searchResponseResultsInnerRating, ..} ) <$> f searchResponseResultsInnerRating
{-# INLINE searchResponseResultsInnerRatingL #-}

-- | 'searchResponseResultsInnerAdultOnly' Lens
searchResponseResultsInnerAdultOnlyL :: Lens_' SearchResponseResultsInner (Maybe Bool)
searchResponseResultsInnerAdultOnlyL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerAdultOnly -> SearchResponseResultsInner { searchResponseResultsInnerAdultOnly, ..} ) <$> f searchResponseResultsInnerAdultOnly
{-# INLINE searchResponseResultsInnerAdultOnlyL #-}

-- | 'searchResponseResultsInnerScreenshots' Lens
searchResponseResultsInnerScreenshotsL :: Lens_' SearchResponseResultsInner (Maybe [Text])
searchResponseResultsInnerScreenshotsL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerScreenshots -> SearchResponseResultsInner { searchResponseResultsInnerScreenshots, ..} ) <$> f searchResponseResultsInnerScreenshots
{-# INLINE searchResponseResultsInnerScreenshotsL #-}

-- | 'searchResponseResultsInnerMicroTrailer' Lens
searchResponseResultsInnerMicroTrailerL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerMicroTrailerL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerMicroTrailer -> SearchResponseResultsInner { searchResponseResultsInnerMicroTrailer, ..} ) <$> f searchResponseResultsInnerMicroTrailer
{-# INLINE searchResponseResultsInnerMicroTrailerL #-}

-- | 'searchResponseResultsInnerGameplay' Lens
searchResponseResultsInnerGameplayL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerGameplayL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerGameplay -> SearchResponseResultsInner { searchResponseResultsInnerGameplay, ..} ) <$> f searchResponseResultsInnerGameplay
{-# INLINE searchResponseResultsInnerGameplayL #-}

-- | 'searchResponseResultsInnerShortDescription' Lens
searchResponseResultsInnerShortDescriptionL :: Lens_' SearchResponseResultsInner (Maybe Text)
searchResponseResultsInnerShortDescriptionL f SearchResponseResultsInner{..} = (\searchResponseResultsInnerShortDescription -> SearchResponseResultsInner { searchResponseResultsInnerShortDescription, ..} ) <$> f searchResponseResultsInnerShortDescription
{-# INLINE searchResponseResultsInnerShortDescriptionL #-}



-- * SearchResponseResultsInnerRating

-- | 'searchResponseResultsInnerRatingMean' Lens
searchResponseResultsInnerRatingMeanL :: Lens_' SearchResponseResultsInnerRating (Maybe Double)
searchResponseResultsInnerRatingMeanL f SearchResponseResultsInnerRating{..} = (\searchResponseResultsInnerRatingMean -> SearchResponseResultsInnerRating { searchResponseResultsInnerRatingMean, ..} ) <$> f searchResponseResultsInnerRatingMean
{-# INLINE searchResponseResultsInnerRatingMeanL #-}

-- | 'searchResponseResultsInnerRatingCount' Lens
searchResponseResultsInnerRatingCountL :: Lens_' SearchResponseResultsInnerRating (Maybe Double)
searchResponseResultsInnerRatingCountL f SearchResponseResultsInnerRating{..} = (\searchResponseResultsInnerRatingCount -> SearchResponseResultsInnerRating { searchResponseResultsInnerRatingCount, ..} ) <$> f searchResponseResultsInnerRatingCount
{-# INLINE searchResponseResultsInnerRatingCountL #-}



-- * SearchResponseSorting

-- | 'searchResponseSortingKey' Lens
searchResponseSortingKeyL :: Lens_' SearchResponseSorting (Maybe Text)
searchResponseSortingKeyL f SearchResponseSorting{..} = (\searchResponseSortingKey -> SearchResponseSorting { searchResponseSortingKey, ..} ) <$> f searchResponseSortingKey
{-# INLINE searchResponseSortingKeyL #-}

-- | 'searchResponseSortingDirection' Lens
searchResponseSortingDirectionL :: Lens_' SearchResponseSorting (Maybe Text)
searchResponseSortingDirectionL f SearchResponseSorting{..} = (\searchResponseSortingDirection -> SearchResponseSorting { searchResponseSortingDirection, ..} ) <$> f searchResponseSortingDirection
{-# INLINE searchResponseSortingDirectionL #-}



-- * SearchResponseSortingOptionsInner

-- | 'searchResponseSortingOptionsInnerName' Lens
searchResponseSortingOptionsInnerNameL :: Lens_' SearchResponseSortingOptionsInner (Maybe Text)
searchResponseSortingOptionsInnerNameL f SearchResponseSortingOptionsInner{..} = (\searchResponseSortingOptionsInnerName -> SearchResponseSortingOptionsInner { searchResponseSortingOptionsInnerName, ..} ) <$> f searchResponseSortingOptionsInnerName
{-# INLINE searchResponseSortingOptionsInnerNameL #-}

-- | 'searchResponseSortingOptionsInnerSort' Lens
searchResponseSortingOptionsInnerSortL :: Lens_' SearchResponseSortingOptionsInner (Maybe Text)
searchResponseSortingOptionsInnerSortL f SearchResponseSortingOptionsInner{..} = (\searchResponseSortingOptionsInnerSort -> SearchResponseSortingOptionsInner { searchResponseSortingOptionsInnerSort, ..} ) <$> f searchResponseSortingOptionsInnerSort
{-# INLINE searchResponseSortingOptionsInnerSortL #-}

-- | 'searchResponseSortingOptionsInnerKey' Lens
searchResponseSortingOptionsInnerKeyL :: Lens_' SearchResponseSortingOptionsInner (Maybe Text)
searchResponseSortingOptionsInnerKeyL f SearchResponseSortingOptionsInner{..} = (\searchResponseSortingOptionsInnerKey -> SearchResponseSortingOptionsInner { searchResponseSortingOptionsInnerKey, ..} ) <$> f searchResponseSortingOptionsInnerKey
{-# INLINE searchResponseSortingOptionsInnerKeyL #-}



-- * SearchSuggestionResponse

-- | 'searchSuggestionResponseResults' Lens
searchSuggestionResponseResultsL :: Lens_' SearchSuggestionResponse (Maybe [SearchSuggestionResponseResultsInner])
searchSuggestionResponseResultsL f SearchSuggestionResponse{..} = (\searchSuggestionResponseResults -> SearchSuggestionResponse { searchSuggestionResponseResults, ..} ) <$> f searchSuggestionResponseResults
{-# INLINE searchSuggestionResponseResultsL #-}



-- * SearchSuggestionResponseResultsInner

-- | 'searchSuggestionResponseResultsInnerId' Lens
searchSuggestionResponseResultsInnerIdL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Int)
searchSuggestionResponseResultsInnerIdL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerId -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerId, ..} ) <$> f searchSuggestionResponseResultsInnerId
{-# INLINE searchSuggestionResponseResultsInnerIdL #-}

-- | 'searchSuggestionResponseResultsInnerYear' Lens
searchSuggestionResponseResultsInnerYearL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Double)
searchSuggestionResponseResultsInnerYearL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerYear -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerYear, ..} ) <$> f searchSuggestionResponseResultsInnerYear
{-# INLINE searchSuggestionResponseResultsInnerYearL #-}

-- | 'searchSuggestionResponseResultsInnerName' Lens
searchSuggestionResponseResultsInnerNameL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Text)
searchSuggestionResponseResultsInnerNameL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerName -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerName, ..} ) <$> f searchSuggestionResponseResultsInnerName
{-# INLINE searchSuggestionResponseResultsInnerNameL #-}

-- | 'searchSuggestionResponseResultsInnerGenre' Lens
searchSuggestionResponseResultsInnerGenreL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Text)
searchSuggestionResponseResultsInnerGenreL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerGenre -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerGenre, ..} ) <$> f searchSuggestionResponseResultsInnerGenre
{-# INLINE searchSuggestionResponseResultsInnerGenreL #-}

-- | 'searchSuggestionResponseResultsInnerImage' Lens
searchSuggestionResponseResultsInnerImageL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Text)
searchSuggestionResponseResultsInnerImageL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerImage -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerImage, ..} ) <$> f searchSuggestionResponseResultsInnerImage
{-# INLINE searchSuggestionResponseResultsInnerImageL #-}

-- | 'searchSuggestionResponseResultsInnerLink' Lens
searchSuggestionResponseResultsInnerLinkL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Text)
searchSuggestionResponseResultsInnerLinkL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerLink -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerLink, ..} ) <$> f searchSuggestionResponseResultsInnerLink
{-# INLINE searchSuggestionResponseResultsInnerLinkL #-}

-- | 'searchSuggestionResponseResultsInnerRating' Lens
searchSuggestionResponseResultsInnerRatingL :: Lens_' SearchSuggestionResponseResultsInner (Maybe SearchResponseResultsInnerRating)
searchSuggestionResponseResultsInnerRatingL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerRating -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerRating, ..} ) <$> f searchSuggestionResponseResultsInnerRating
{-# INLINE searchSuggestionResponseResultsInnerRatingL #-}

-- | 'searchSuggestionResponseResultsInnerAdultOnly' Lens
searchSuggestionResponseResultsInnerAdultOnlyL :: Lens_' SearchSuggestionResponseResultsInner (Maybe Bool)
searchSuggestionResponseResultsInnerAdultOnlyL f SearchSuggestionResponseResultsInner{..} = (\searchSuggestionResponseResultsInnerAdultOnly -> SearchSuggestionResponseResultsInner { searchSuggestionResponseResultsInnerAdultOnly, ..} ) <$> f searchSuggestionResponseResultsInnerAdultOnly
{-# INLINE searchSuggestionResponseResultsInnerAdultOnlyL #-}



-- * SimilarGamesResponse

-- | 'similarGamesResponseResults' Lens
similarGamesResponseResultsL :: Lens_' SimilarGamesResponse (Maybe [SearchResponseResultsInner])
similarGamesResponseResultsL f SimilarGamesResponse{..} = (\similarGamesResponseResults -> SimilarGamesResponse { similarGamesResponseResults, ..} ) <$> f similarGamesResponseResults
{-# INLINE similarGamesResponseResultsL #-}


