server:
  port: 8081

spring:
  ai:
    mcp:
      server:
        name: geocoder-mcp-server
        version: 1.0.0

logging:
  level:
    es.omarall: DEBUG
    org.springframework.ai: DEBUG