# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GameBrainAPI.Model.SearchResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :sorting,
    :active_filter_options,
    :query,
    :total_results,
    :limit,
    :offset,
    :results,
    :filter_options,
    :sorting_options
  ]

  @type t :: %__MODULE__{
    :sorting => GameBrainAPI.Model.SearchResponseSorting.t | nil,
    :active_filter_options => [GameBrainAPI.Model.SearchResponseActiveFilterOptionsInner.t] | nil,
    :query => String.t | nil,
    :total_results => integer() | nil,
    :limit => integer() | nil,
    :offset => integer() | nil,
    :results => [GameBrainAPI.Model.SearchResponseResultsInner.t] | nil,
    :filter_options => [GameBrainAPI.Model.SearchResponseFilterOptionsInner.t] | nil,
    :sorting_options => [GameBrainAPI.Model.SearchResponseSortingOptionsInner.t] | nil
  }

  alias GameBrainAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:sorting, :struct, GameBrainAPI.Model.SearchResponseSorting)
     |> Deserializer.deserialize(:active_filter_options, :list, GameBrainAPI.Model.SearchResponseActiveFilterOptionsInner)
     |> Deserializer.deserialize(:results, :list, GameBrainAPI.Model.SearchResponseResultsInner)
     |> Deserializer.deserialize(:filter_options, :list, GameBrainAPI.Model.SearchResponseFilterOptionsInner)
     |> Deserializer.deserialize(:sorting_options, :list, GameBrainAPI.Model.SearchResponseSortingOptionsInner)
  end
end

