[project]
name = "python-local"
version = "0.1.0"
description = "An MCP Server to run python locally"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "mcp>=1.1.0",]
[[project.authors]]
name = "Alex Velikanov"
email = "alex25368@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
python-local = "python_local:main"
